import { useEffect, useState, type ReactNode } from 'react';
import { FileSpreadsheet } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Alert, Button, DataTable, LoadingSpinner, Modal } from '../ui';
import { getInventoryReportDetail } from '../../services/inventoryReportService';
import type { InventoryReportDetail, InventoryReportRow } from '../../types/inventoryReport';
import { formatCurrency } from '../../utils/format';
import { getErrorMessage } from '../../utils/errors';
import { InventoryStatusBadge } from './inventoryReportShared';
import { formatInventoryPriceRange } from '../../utils/inventoryReportFormat';

export function InventoryReportDetailModal({ product, threshold, onClose }: { product: InventoryReportRow; threshold: number; onClose: () => void }) {
  const [detail, setDetail] = useState<InventoryReportDetail>(); const [error, setError] = useState<string>();
  useEffect(() => { let active = true; void getInventoryReportDetail(product, threshold).then((value) => { if (active) setDetail(value); }).catch((reason) => { if (active) setError(getErrorMessage(reason, 'Unable to load inventory details.')); }); return () => { active = false; }; }, [product, threshold]);
  return <Modal title={product.product_name} onClose={onClose} size="xl" respectSidebar>{error ? <Alert message={error} /> : !detail ? <div className="flex min-h-64 items-center justify-center"><LoadingSpinner /></div> : <div className="space-y-6">
    <section><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold text-dashboard-text-primary">Product Information</h3><Link to={`/inventory/${product.product_id}`}><Button variant="secondary" size="sm"><FileSpreadsheet size={16} />View Matrix</Button></Link></div><Info values={[['Product Code', product.product_code], ['Product Name', product.product_name], ['Item Article', product.item_article || '—'], ['Category', product.category_name], ['Brand', product.brand_name], ['Description', product.description || '—']]} /></section>
    <section><h3 className="mb-3 font-semibold text-dashboard-text-primary">Inventory Summary</h3><Info values={[['Total Variants', String(product.variant_count)], ['Total Stock', `${product.total_stock} units`], ['Cost Value', formatCurrency(product.cost_value)], ['Selling Value', formatCurrency(product.selling_value)], ['Potential Profit', formatCurrency(product.potential_profit)], ['Cost Price', formatInventoryPriceRange(product.min_cost, product.max_cost)], ['Selling Price', formatInventoryPriceRange(product.min_selling, product.max_selling)]]} /></section>
    {(product.missing_cost_count > 0 || product.missing_selling_count > 0) && <Alert message={`${product.missing_cost_count} variant(s) missing cost price · ${product.missing_selling_count} variant(s) missing selling price`} />}
    <section><h3 className="mb-3 font-semibold text-dashboard-text-primary">Variant Inventory</h3><DataTable columns={[{ key: 'size', header: 'Size' }, { key: 'colour', header: 'Colour' }, { key: 'barcode', header: 'Barcode Number' }, { key: 'stock', header: 'Stock' }, { key: 'cost', header: 'Cost Price' }, { key: 'selling', header: 'Selling Price' }, { key: 'cost-value', header: 'Cost Value' }, { key: 'selling-value', header: 'Selling Value' }, { key: 'status', header: 'Stock Status' }]} isEmpty={!detail.variants.length}>{detail.variants.map((variant) => <tr key={variant.id} className={variant.stock_status === 'negative_stock' ? 'bg-red-500/10' : variant.stock_status === 'low_stock' ? 'bg-amber-500/5' : ''}><Cell>{variant.size}</Cell><Cell>{variant.color}</Cell><Cell>{variant.barcode_number || '—'}</Cell><Cell strong>{variant.stock_quantity}</Cell><Cell>{variant.cost_price === null ? 'Missing' : formatCurrency(variant.cost_price)}</Cell><Cell>{variant.selling_price === null ? 'Missing' : formatCurrency(variant.selling_price)}</Cell><Cell>{variant.cost_value === null ? '—' : formatCurrency(variant.cost_value)}</Cell><Cell>{variant.selling_value === null ? '—' : formatCurrency(variant.selling_value)}</Cell><Cell><InventoryStatusBadge status={variant.stock_status} /></Cell></tr>)}</DataTable></section>
  </div>}</Modal>;
}
function Info({ values }: { values: Array<[string, string]> }) { return <div className="grid gap-3 rounded-xl border border-white/10 bg-white/[.03] p-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(([name, value]) => <div key={name}><p className="text-xs uppercase tracking-wide text-dashboard-text-label">{name}</p><p className="mt-1 break-words text-sm font-medium text-dashboard-text-primary">{value}</p></div>)}</div>; }
function Cell({ children, strong = false }: { children: ReactNode; strong?: boolean }) { return <td className={`whitespace-nowrap px-4 py-3 text-sm ${strong ? 'font-semibold text-dashboard-text-primary' : 'text-dashboard-text-sub'}`}>{children}</td>; }
