import { useEffect, useState } from 'react';
import { Alert, DataTable, LoadingSpinner, Modal } from '../ui';
import { getPurchaseReportDetail } from '../../services/purchaseReportService';
import type { PurchaseReportDetail } from '../../types/purchaseReport';
import { formatCurrency, formatDate, formatDateTime } from '../../utils/format';
import { getErrorMessage } from '../../utils/errors';

const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
export function PurchaseReportDetailModal({ purchaseId, onClose }: { purchaseId: string; onClose: () => void }) {
  const [detail, setDetail] = useState<PurchaseReportDetail | null>(null); const [error, setError] = useState<string>();
  useEffect(() => { let active = true; void getPurchaseReportDetail(purchaseId).then((value) => { if (active) setDetail(value); }).catch((reason) => { if (active) setError(getErrorMessage(reason, 'Unable to load purchase details.')); }); return () => { active = false; }; }, [purchaseId]);
  return <Modal title={detail?.purchase_number || 'Purchase Details'} onClose={onClose} size="xl" respectSidebar>
    {error ? <Alert message={error} /> : !detail ? <div className="flex min-h-64 items-center justify-center"><LoadingSpinner /></div> : <div className="space-y-6">
      <section><h3 className="mb-3 font-semibold text-dashboard-text-primary">Purchase Information</h3><Info values={[['Purchase Number', detail.purchase_number], ['Purchase Date', formatDate(detail.purchase_date)], ['Supplier Invoice Number', detail.supplier_invoice_number || '—'], ['Status', label(detail.status)], ['Created By', detail.created_by], ['Created Date', formatDateTime(detail.created_at)]]} /></section>
      <section><h3 className="mb-3 font-semibold text-dashboard-text-primary">Supplier</h3><Info values={[['Supplier Name', detail.supplier_name], ['Supplier Code', detail.supplier_code || '—'], ['Phone', detail.supplier_phone || '—'], ['Address', detail.supplier_address || '—']]} /></section>
      <section><h3 className="mb-3 font-semibold text-dashboard-text-primary">Purchased Items</h3><DataTable columns={[{ key: 'product', header: 'Product' }, { key: 'article', header: 'Article' }, { key: 'size', header: 'Size' }, { key: 'colour', header: 'Colour' }, { key: 'barcode', header: 'Barcode Number' }, { key: 'qty', header: 'Quantity' }, { key: 'cost', header: 'Cost Price' }, { key: 'selling', header: 'Selling Price' }, { key: 'discount', header: 'Discount' }, { key: 'total', header: 'Line Total' }]} isEmpty={!detail.items.length}>{detail.items.map((item) => <tr key={item.id}><Cell strong>{item.product_name}</Cell><Cell>{item.item_article || '—'}</Cell><Cell>{item.size || '—'}</Cell><Cell>{item.color || '—'}</Cell><Cell>{item.barcode_number || '—'}</Cell><Cell>{item.quantity}</Cell><Cell>{formatCurrency(item.cost_price)}</Cell><Cell>{item.selling_price == null ? '—' : formatCurrency(item.selling_price)}</Cell><Cell>{formatCurrency(item.line_discount)}</Cell><Cell strong>{formatCurrency(item.line_total)}</Cell></tr>)}</DataTable></section>
      <section className="ml-auto grid max-w-lg grid-cols-2 gap-x-6 gap-y-2 rounded-xl border border-white/10 bg-white/[.03] p-4">{[['Subtotal', detail.subtotal], ['Discount', detail.discount_amount], ['Additional Cost', detail.additional_cost], ['Grand Total', detail.total_amount], ['Paid', detail.paid_amount], ['Balance', detail.balance_amount]].map(([name, value]) => <div className="contents" key={String(name)}><span className="text-dashboard-text-sub">{name}</span><strong className="text-right text-dashboard-text-primary">{formatCurrency(Number(value))}</strong></div>)}</section>
      <section><h3 className="mb-3 font-semibold text-dashboard-text-primary">Payment History</h3><DataTable columns={[{ key: 'date', header: 'Date' }, { key: 'method', header: 'Method' }, { key: 'amount', header: 'Amount' }, { key: 'reference', header: 'Reference' }, { key: 'by', header: 'Recorded By' }]} isEmpty={!detail.payments.length} emptyMessage="No payments recorded.">{detail.payments.map((payment) => <tr key={payment.id}><Cell>{formatDate(payment.payment_date)}</Cell><Cell>{payment.payment_method}</Cell><Cell strong>{formatCurrency(payment.amount)}</Cell><Cell>{payment.reference_number || '—'}</Cell><Cell>{payment.recorded_by}</Cell></tr>)}</DataTable></section>
    </div>}
  </Modal>;
}

function Info({ values }: { values: Array<[string, string]> }) { return <div className="grid gap-3 rounded-xl border border-white/10 bg-white/[.03] p-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(([name, value]) => <div key={name}><p className="text-xs uppercase tracking-wide text-dashboard-text-label">{name}</p><p className="mt-1 break-words text-sm font-medium text-dashboard-text-primary">{value}</p></div>)}</div>; }
function Cell({ children, strong = false }: { children: React.ReactNode; strong?: boolean }) { return <td className={`whitespace-nowrap px-4 py-3 text-sm ${strong ? 'font-semibold text-dashboard-text-primary' : 'text-dashboard-text-sub'}`}>{children}</td>; }
