import { useMemo, useState, type ReactElement } from 'react';
import { CircleDollarSign, Package, TrendingUp } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, Cell, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { ReportInvoice } from '../../types/salesReport';
import { formatCurrency } from '../../utils/format';

const COLORS=['#38bdf8','#8b5cf6','#22c55e','#f59e0b','#f43f5e','#06b6d4','#a3e635','#fb7185'];
const axis={tick:{fill:'#94a3b8',fontSize:11},axisLine:false,tickLine:false};

export function SalesReportCharts({invoices}:{invoices:ReportInvoice[]}){
 const [metric,setMetric]=useState<'financial'|'quantity'>('financial');
 const data=useMemo(()=>analytics(invoices),[invoices]);
 return <section className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-violet-300">Visual analytics</p><h2 className="mt-1 text-lg font-semibold">Performance trends</h2><p className="mt-1 text-xs text-dashboard-text-sub">Automatically grouped {data.granularity}; missing periods are filled with zero.</p></div><div className="flex rounded-xl border border-white/10 bg-black/10 p-1"><Toggle active={metric==='financial'} onClick={()=>setMetric('financial')} icon={<CircleDollarSign size={14}/>} label="Financial"/><Toggle active={metric==='quantity'} onClick={()=>setMetric('quantity')} icon={<Package size={14}/>} label="Quantity"/></div></div>
 <div className="grid gap-4 xl:grid-cols-[1.65fr_1fr]"><Panel title={metric==='financial'?'Revenue, cost and profit':'Quantity sold trend'} subtitle={`${data.trend.length} reporting periods`} icon={<TrendingUp size={17}/>}>{metric==='financial'?<AreaChart data={data.trend}><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#38bdf8" stopOpacity={.38}/><stop offset="1" stopColor="#38bdf8" stopOpacity={0}/></linearGradient></defs><Grid/><XAxis dataKey="label" {...axis}/><YAxis {...axis} tickFormatter={compact}/><Tooltip content={<Tip currency/>}/><Legend/><Area type="monotone" dataKey="revenue" name="Net revenue" stroke="#38bdf8" strokeWidth={2.5} fill="url(#salesFill)"/><Line type="monotone" dataKey="cost" name="Cost" stroke="#f59e0b" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="profit" name="Profit" stroke="#22c55e" strokeWidth={2} dot={false}/></AreaChart>:<AreaChart data={data.trend}><Grid/><XAxis dataKey="label" {...axis}/><YAxis {...axis} allowDecimals={false}/><Tooltip content={<Tip/>}/><Area type="monotone" dataKey="quantity" name="Net quantity" stroke="#a78bfa" strokeWidth={2.5} fill="#8b5cf633"/></AreaChart>}</Panel><Panel title="Sales by payment method" subtitle="Actual payment components received" icon={<CircleDollarSign size={17}/>}><PieChart><Pie data={data.payments} dataKey="value" nameKey="name" cx="50%" cy="44%" innerRadius={56} outerRadius={86} paddingAngle={3}>{data.payments.map((x,i)=><Cell key={x.name} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip content={<Tip currency/>}/><Legend verticalAlign="bottom" iconType="circle"/></PieChart></Panel></div>
 </section>
}

function Panel({title,subtitle,icon,children}:{title:string;subtitle:string;icon:ReactElement;children:ReactElement}){return <div className="glass-card min-w-0 overflow-hidden"><div className="relative z-10 flex items-center gap-3 border-b border-white/10 px-5 py-4"><div className="rounded-xl bg-white/[.06] p-2 text-sky-300">{icon}</div><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-.5 text-[11px] text-dashboard-text-sub">{subtitle}</p></div></div><div className="relative z-10 min-w-0 p-3 md:p-5"><ResponsiveContainer width="100%" height={280} minWidth={240}>{children}</ResponsiveContainer></div></div>}
function Toggle({active,onClick,icon,label}:{active:boolean;onClick:()=>void;icon:ReactElement;label:string}){return <button onClick={onClick} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs transition ${active?'bg-white/10 text-white':'text-dashboard-text-sub hover:text-white'}`}>{icon}{label}</button>}
function Grid(){return <CartesianGrid stroke="rgba(148,163,184,.12)" strokeDasharray="4 4" vertical={false}/>}
function Tip({active,payload,label,currency=false}:any){if(!active||!payload?.length)return null;return <div className="rounded-xl border border-white/15 bg-slate-950/95 px-3 py-2 shadow-2xl"><p className="mb-1 text-xs font-semibold">{label||payload[0]?.payload?.name}</p>{payload.map((p:any)=><div key={p.dataKey} className="flex min-w-36 justify-between gap-5 text-xs"><span style={{color:p.color}}>{p.name}</span><b>{currency?formatCurrency(Number(p.value)):Number(p.value).toLocaleString()}</b></div>)}</div>}
function compact(v:number){return Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(v)}

function analytics(invoices:ReportInvoice[]){const active=invoices.filter(x=>x.status!=='cancelled');const dates=active.map(x=>new Date(x.created_at));const min=dates.length?new Date(Math.min(...dates.map(x=>x.getTime()))):new Date();const max=dates.length?new Date(Math.max(...dates.map(x=>x.getTime()))):new Date();const days=Math.max(1,Math.ceil((max.getTime()-min.getTime())/86400000));const granularity=days<=1?'hourly':days<=31?'daily':days<=183?'weekly':'monthly';
 const key=(d:Date)=>{if(granularity==='hourly')return `${d.toLocaleDateString('en-CA')}T${String(d.getHours()).padStart(2,'0')}`;if(granularity==='daily')return d.toLocaleDateString('en-CA');if(granularity==='weekly'){const x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));return x.toLocaleDateString('en-CA')}return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};const label=(k:string)=>granularity==='hourly'?`${k.slice(11)}:00`:granularity==='monthly'?new Date(`${k}-01`).toLocaleDateString(undefined,{month:'short',year:'2-digit'}):new Date(`${k}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'});
 const trend=new Map<string,{key:string;label:string;revenue:number;cost:number;profit:number;quantity:number}>();const cursor=new Date(min);cursor.setMinutes(0,0,0);while(cursor<=max){const k=key(cursor);trend.set(k,{key:k,label:label(k),revenue:0,cost:0,profit:0,quantity:0});if(granularity==='hourly')cursor.setHours(cursor.getHours()+1);else if(granularity==='daily')cursor.setDate(cursor.getDate()+1);else if(granularity==='weekly')cursor.setDate(cursor.getDate()+7);else cursor.setMonth(cursor.getMonth()+1)}for(const x of active){const k=key(new Date(x.created_at));const p=trend.get(k)??{key:k,label:label(k),revenue:0,cost:0,profit:0,quantity:0};p.revenue+=x.net_amount;p.cost+=x.cost_of_goods??0;p.profit+=x.gross_profit??0;p.quantity+=x.items.reduce((s,i)=>s+i.net_quantity,0);trend.set(k,p)}
 const sales=(pick:(x:ReportInvoice)=>string,val:(x:ReportInvoice)=>number)=>Object.values(active.reduce<Record<string,{name:string;value:number}>>((a,x)=>{const n=pick(x)||'Other';a[n]??={name:n,value:0};a[n].value+=val(x);return a},{})).sort((a,b)=>b.value-a.value).slice(0,8);const items=(mode:'category'|'selling'|'profit')=>{const a:Record<string,{name:string;value:number}>={};for(const x of active)for(const i of x.items){const n=mode==='category'?(i.category||'Uncategorized'):i.product_name;a[n]??={name:n,value:0};a[n].value+=mode==='category'?i.net_revenue:mode==='selling'?i.net_quantity:(i.profit??0)}return Object.values(a).sort((x,y)=>y.value-x.value).slice(0,8)};
 return {granularity,trend:[...trend.values()].sort((a,b)=>a.key.localeCompare(b.key)),payments:sales(x=>x.payment_method,x=>x.amount_paid),cashiers:sales(x=>x.cashier_name,x=>x.net_amount),categories:items('category'),selling:items('selling'),profitable:items('profit')}}
