import { supabase } from './supabase'; import type { BankDeposit,CashRegisterSession,CashRegisterSummary } from '../types/cashRegister';
export async function getCurrentRegister(){const {data,error}=await supabase.rpc('get_cash_register_summary',{p_session_id:null});if(error)throw error;return data as CashRegisterSummary|null}
export async function getRegisterSummary(id:string){const {data,error}=await supabase.rpc('get_cash_register_summary',{p_session_id:id});if(error)throw error;return data as CashRegisterSummary}
export async function openRegister(openingBalance:number,notes:string){const {data,error}=await supabase.rpc('open_cash_register',{p_opening_balance:openingBalance,p_notes:notes});if(error)throw error;return data as string}
export async function closeRegister(id:string,actualCash:number,notes:string){const {data,error}=await supabase.rpc('close_cash_register',{p_session_id:id,p_actual_cash:actualCash,p_notes:notes});if(error)throw error;return data as CashRegisterSummary}
export async function addCashExpense(sessionId:string,amount:number,description:string){const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('cash_register_expenses').insert({session_id:sessionId,user_id:user?.id,amount,description});if(error)throw error}
export async function recordBankDeposit(sessionId:string,amount:number,bankName:string,reference:string,notes:string){const{error}=await supabase.rpc('record_bank_deposit',{p_session_id:sessionId,p_amount:amount,p_bank_name:bankName,p_reference:reference||null,p_notes:notes||null});if(error)throw error}
export async function getSessionBankDeposits(sessionId:string){const{data,error}=await supabase.from('cash_register_movements').select('id,cash_register_id,amount,bank_name,reference,notes,created_at,created_by,recorder:profiles!cash_register_movements_created_by_fkey(full_name,email)').eq('cash_register_id',sessionId).eq('movement_type','bank_deposit').order('created_at',{ascending:false});if(error)throw error;return(data??[]).map((x:any)=>({...x,amount:Number(x.amount),recorded_by:x.recorder?.full_name||x.recorder?.email||'Cashier'}))as BankDeposit[]}
export async function getRegisterSessions(page=1,pageSize=20){const {data,error,count}=await supabase.from('cash_register_sessions').select('*,cashier:profiles(full_name,email)',{count:'exact'}).order('opening_time',{ascending:false}).range((page-1)*pageSize,page*pageSize-1);if(error)throw error;return{rows:(data??[]) as unknown as CashRegisterSession[],count:count??0}}
