import{jsPDF}from'jspdf';import autoTable from'jspdf-autotable';
import type{BankDepositReportRow,CashupDetail,CashupExportData,CashupFilters,CashupRow}from'../types/cashupReport';
import{downloadBlob}from'./salesReportService';import{cashupRange}from'../utils/cashupReportDates';import{cashupStatusLabel}from'../utils/cashupFormat';
const dq=String.fromCharCode(34),q=(v:unknown)=>dq+String(v??'').replaceAll(dq,dq+dq)+dq,money=(v:number|null)=>v===null?'—':`LKR ${v.toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const headers=['Cashup No','Date','Cashier','Opening Cash','Sales','Cash Sales','Cash Expenses','Bank Deposits','Expected Cash','Counted Cash','Difference','Status'];
const row=(r:CashupRow):Array<string|number>=>[r.cashup_number,new Date(r.opening_time).toLocaleDateString(),r.cashier_name,r.opening_cash,r.total_sales,r.cash_sales,r.cash_expenses,r.bank_deposits,r.expected_cash,r.counted_cash??'',r.difference??'',cashupStatusLabel(r)];
export function exportCashupCsv(d:CashupExportData){downloadBlob('cashup-report.csv','\ufeff'+[headers,...d.rows.map(row)].map(r=>r.map(q).join(',')).join('\r\n'),'text/csv;charset=utf-8')}
const xml=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'),sheet=(n:string,rows:Array<Array<string|number>>)=>`<Worksheet ss:Name='${n}'><Table>${rows.map(r=>`<Row>${r.map(v=>`<Cell><Data ss:Type='${typeof v==='number'?'Number':'String'}'>${xml(v)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet>`;
export function exportCashupExcel(d:CashupExportData){const deposits=d.details.flatMap(x=>x.deposits.map(v=>[x.session.cashup_number,new Date(v.date).toLocaleDateString(),new Date(v.date).toLocaleTimeString(),v.bank,v.reference||'',v.amount,v.recorded_by,v.notes||'']));const payments=d.rows.map(r=>[r.cashup_number,r.cash_sales,r.card_sales,r.bank_sales,r.credit_sales,r.other_sales]);downloadBlob('cashup-report.xls',`<?xml version='1.0'?><Workbook xmlns='urn:schemas-microsoft-com:office:spreadsheet' xmlns:ss='urn:schemas-microsoft-com:office:spreadsheet'>${sheet('Cashup Summary',[headers,...d.rows.map(row)])}${sheet('Payment Breakdown',[['Cashup No','Cash','Card','Bank Transfer','Credit','Other'],...payments])}${sheet('Bank Deposits',[['Cashup','Date','Time','Bank','Reference','Amount','Recorded By','Notes'],...deposits])}</Workbook>`,'application/vnd.ms-excel')}
const head=(doc:jsPDF,title:string,range:string)=>{const w=doc.internal.pageSize.getWidth();doc.setFillColor(5,44,36);doc.rect(0,0,w,27,'F');doc.setTextColor(255,255,255);doc.setFontSize(15);doc.text('SHOE GALLERY',12,10);doc.setFontSize(11);doc.text(title,w-12,10,{align:'right'});doc.setFontSize(8);doc.text(range,12,18)};
export function downloadCashupPdf(d:CashupExportData,f:CashupFilters){const doc=new jsPDF({orientation:'landscape'});head(doc,'Cashup Report',cashupRange(f.startDate,f.endDate));autoTable(doc,{startY:32,head:[['Sessions','Sales','Cash','Expenses','Deposits','Expected','Counted','Difference']],body:[[d.summary.sessions,money(d.summary.total_sales),money(d.summary.cash_sales),money(d.summary.cash_expenses),money(d.summary.bank_deposits),money(d.summary.expected_cash),money(d.summary.counted_cash),money(d.summary.cash_difference)]],headStyles:{fillColor:[5,44,36]}});autoTable(doc,{head:[['Cashup','Cashier','Opening','Cash Sales','Expenses','Deposits','Expected','Actual','Difference','Status']],body:d.rows.map(r=>[r.cashup_number,r.cashier_name,money(r.opening_cash),money(r.cash_sales),money(r.cash_expenses),money(r.bank_deposits),money(r.expected_cash),money(r.counted_cash),money(r.difference),cashupStatusLabel(r)]),headStyles:{fillColor:[5,44,36]},styles:{fontSize:7}});doc.save('cashup-report.pdf')}
export function downloadIndividualCashupPdf(d:CashupDetail){const doc=new jsPDF({orientation:'landscape'}),r=d.session;head(doc,'Cashup Closing Report',`${r.cashup_number} · ${r.cashier_name}`);autoTable(doc,{startY:32,head:[['Opening','Cash Sales','Refunds','Expenses','Deposits','Expected','Counted','Difference','Status']],body:[[money(r.opening_cash),money(r.cash_sales),money(r.cash_refunds),money(r.cash_expenses),money(r.bank_deposits),money(r.expected_cash),money(r.counted_cash),money(r.difference),cashupStatusLabel(r)]],headStyles:{fillColor:[5,44,36]}});if(d.deposits.length)autoTable(doc,{head:[['Date','Time','Bank','Reference','Amount','Recorded By','Notes']],body:d.deposits.map(v=>[new Date(v.date).toLocaleDateString(),new Date(v.date).toLocaleTimeString(),v.bank,v.reference||'—',money(v.amount),v.recorded_by,v.notes||'—']),headStyles:{fillColor:[5,44,36]},styles:{fontSize:7}});doc.save(`cashup-${r.cashup_number}.pdf`)}
export function downloadBankDepositsPdf(rows:BankDepositReportRow[],range:string){const doc=new jsPDF({orientation:'landscape'});head(doc,'Bank Deposit Report',range);autoTable(doc,{startY:32,head:[['Date','Time','Cashup','Cashier','Bank','Reference','Amount']],body:rows.map(v=>[new Date(v.date).toLocaleDateString(),new Date(v.date).toLocaleTimeString(),v.cashup,v.cashier,v.bank,v.reference||'—',money(v.amount)]),headStyles:{fillColor:[5,44,36]}});doc.setFontSize(10);doc.text(`Total Deposited: ${money(rows.reduce((a,v)=>a+v.amount,0))}`,14,doc.internal.pageSize.getHeight()-8);doc.save('bank-deposit-report.pdf')}
export function exportBankDepositsExcel(rows:BankDepositReportRow[]){const data:Array<Array<string|number>>=[['Date','Time','Cashup','Cashier','Bank','Reference','Amount','Notes'],...rows.map(v=>[new Date(v.date).toLocaleDateString(),new Date(v.date).toLocaleTimeString(),v.cashup,v.cashier,v.bank,v.reference||'',v.amount,v.notes||''])];downloadBlob('bank-deposit-report.xls',`<?xml version='1.0'?><Workbook xmlns='urn:schemas-microsoft-com:office:spreadsheet' xmlns:ss='urn:schemas-microsoft-com:office:spreadsheet'>${sheet('Bank Deposits',data)}</Workbook>`,'application/vnd.ms-excel')}
