import { supabase } from './supabase';
import type { BankDepositReportRow,CashierCashup,CashupDeposit,CashupDetail,CashupExportData,CashupFilters,CashupOptions,CashupPageSize,CashupResult,CashupRow,CashupSort,DailyCashup } from '../types/cashupReport';
import { validateCashupRows } from '../utils/cashupValidation';
import { calculateCardFee,calculateNetCardAmount } from '../utils/cardFee';
import { autoCloseExpiredRegisters } from './cashRegisterService';
const n=(v:unknown)=>Number(v??0),nn=(v:unknown)=>v==null?null:Number(v);

function normalize(v:unknown):CashupResult{
 const x=(v??{})as any;
 const rows:CashupRow[]=(x.rows??[]).map((r:any)=>({...r,opening_cash:n(r.opening_cash),total_invoices:n(r.total_invoices),items_sold:n(r.items_sold),gross_sales:n(r.gross_sales),discounts:n(r.discounts),total_sales:n(r.total_sales),cash_sales:n(r.cash_sales),card_sales:n(r.card_sales),card_processing_fees:n(r.card_processing_fees),net_card_amount:n(r.net_card_amount),bank_sales:n(r.bank_sales),credit_sales:n(r.credit_sales),other_sales:n(r.other_sales),cash_refunds:n(r.cash_refunds),cash_expenses:n(r.cash_expenses),bank_deposits:n(r.bank_deposits),expected_cash:n(r.expected_cash),counted_cash:nn(r.counted_cash),difference:nn(r.difference)}));
 const s=x.summary??{};validateCashupRows(rows);
 const daily:DailyCashup[]=(x.daily??[]).map((d:any)=>({...d,sessions:n(d.sessions),sales:n(d.sales),cash:n(d.cash),card:n(d.card),card_processing_fees:n(d.card_processing_fees),net_card_amount:n(d.net_card_amount),transfer:n(d.transfer),credit:n(d.credit),expected_cash:n(d.expected_cash),counted_cash:n(d.counted_cash),difference:n(d.difference)}));
 const cashiers:CashierCashup[]=(x.cashiers??[]).map((c:any)=>({...c,sessions:n(c.sessions),invoices:n(c.invoices),sales:n(c.sales),cash_collected:n(c.cash_collected),difference:n(c.difference)}));
 return{rows,total:n(x.total),summary:{sessions:n(s.sessions),total_sales:n(s.total_sales),cash_sales:n(s.cash_sales),card_sales:n(s.card_sales),card_processing_fees:n(s.card_processing_fees),net_card_amount:n(s.net_card_amount),bank_sales:n(s.bank_sales),credit_sales:n(s.credit_sales),cash_expenses:n(s.cash_expenses),bank_deposits:n(s.bank_deposits),expected_cash:n(s.expected_cash),counted_cash:n(s.counted_cash),cash_difference:n(s.cash_difference)},daily,cashiers};
}
export async function getCashupReport(f:CashupFilters,page=1,size:CashupPageSize=25,sort:CashupSort='newest'){if(f.startDate&&f.endDate&&f.startDate>f.endDate)throw new Error('From date cannot be after To date.');await autoCloseExpiredRegisters();const{data,error}=await supabase.rpc('get_cashup_report',{p_start_date:f.startDate||null,p_end_date:f.endDate||null,p_search:f.search.trim()||null,p_cashier_id:f.cashierId||null,p_status:f.status||null,p_page:page,p_page_size:size,p_sort:sort});if(error)throw error;const result=normalize(data);if(!result.rows.length)return result;const{data:flags,error:flagsError}=await supabase.from('cash_register_sessions').select('id,auto_closed,closed_by_type').in('id',result.rows.map(row=>row.session_id));if(flagsError)throw flagsError;const byId=new Map((flags??[]).map(flag=>[flag.id,flag]));return{...result,rows:result.rows.map(row=>{const flag=byId.get(row.session_id);const autoClosed=Boolean(flag?.auto_closed);return{...row,auto_closed:autoClosed,closed_by_type:(flag?.closed_by_type??null)as CashupRow['closed_by_type'],difference_status:autoClosed?'auto_closed':row.difference_status}})}}
export async function getCashupOptions():Promise<CashupOptions>{const{data,error}=await supabase.from('profiles').select('id,full_name,email').order('full_name');if(error)throw error;return{cashiers:(data??[]).map(x=>({id:x.id,name:x.full_name||x.email||'Cashier'}))}}
export async function getBankDepositReport():Promise<BankDepositReportRow[]>{const{data,error}=await supabase.from('cash_register_movements').select('id,created_at,bank_name,reference,amount,notes,created_by,recorder:profiles!cash_register_movements_created_by_fkey(full_name,email),session:cash_register_sessions!cash_register_movements_cash_register_id_fkey(id,user_id,cashier:profiles(full_name,email))').eq('movement_type','bank_deposit').order('created_at',{ascending:false}).limit(5000);if(error)throw error;return(data??[]).map((x:any)=>({id:x.id,date:x.created_at,bank:x.bank_name,reference:x.reference,amount:n(x.amount),recorded_by:x.recorder?.full_name||x.recorder?.email||'Cashier',notes:x.notes,cashup:`CS-${String(x.session?.id||'').replaceAll('-','').slice(0,8).toUpperCase()}`,cashier:x.session?.cashier?.full_name||x.session?.cashier?.email||'Cashier',cashier_id:x.session?.user_id||x.created_by}))}

export async function getCashupDetail(session:CashupRow):Promise<CashupDetail>{
 const end=session.closing_time||new Date().toISOString();
 const[sr,rr,er,dr]=await Promise.all([
  supabase.from('sales').select('id,invoice_number,created_at,total_amount,discount_amount,card_payment_fee,status,customer:customers(name),cashier:profiles(full_name,email),sale_items(quantity,line_subtotal,selling_price),sale_payments(payment_method,amount)').eq('user_id',session.user_id).gte('created_at',session.opening_time).lt('created_at',end).in('status',['completed','partially_returned','fully_returned']).order('created_at'),
  supabase.from('sale_refunds').select('id,refund_date,refund_method,amount,return:sales_returns(return_number,sale:sales(invoice_number))').eq('refunded_by',session.user_id).gte('refund_date',session.opening_time).lt('refund_date',end).order('refund_date'),
  supabase.from('cash_register_expenses').select('id,expense_time,description,amount,user:profiles(full_name,email)').eq('session_id',session.session_id).order('expense_time'),
  supabase.from('cash_register_movements').select('id,created_at,bank_name,reference,amount,notes,recorder:profiles!cash_register_movements_created_by_fkey(full_name,email)').eq('cash_register_id',session.session_id).eq('movement_type','bank_deposit').order('created_at')
 ]);
 for(const r of[sr,rr,er,dr])if(r.error)throw r.error;
 const sales=(sr.data??[]).map((s:any)=>{const items=s.sale_items??[],payments=s.sale_payments??[],grossCard=Math.max(payments.filter((p:any)=>p.payment_method==='card').reduce((a:number,p:any)=>a+n(p.amount),0)-n(s.card_payment_fee),0);return{id:s.id,invoice_number:s.invoice_number,created_at:s.created_at,customer_name:s.customer?.name||'Walk-in Customer',payment:[...new Set(payments.map((p:any)=>p.payment_method))].join(', ')||'Credit',total:Math.max(n(s.total_amount)-n(s.card_payment_fee),0),cashier:s.cashier?.full_name||s.cashier?.email||session.cashier_name,status:s.status,items:items.length,quantity:items.reduce((a:number,i:any)=>a+n(i.quantity),0),gross:items.reduce((a:number,i:any)=>a+n(i.line_subtotal??n(i.selling_price)*n(i.quantity)),0),discount:n(s.discount_amount),gross_card_amount:grossCard,card_processing_fee:calculateCardFee(grossCard),net_card_amount:calculateNetCardAmount(grossCard)}});
 const refunds=(rr.data??[]).map((r:any)=>({id:r.id,return_number:r.return?.return_number||'—',invoice:r.return?.sale?.invoice_number||'—',date:r.refund_date,method:r.refund_method,amount:n(r.amount),processed_by:session.cashier_name}));
 const expenses=(er.data??[]).map((e:any)=>({id:e.id,date:e.expense_time,description:e.description,amount:n(e.amount),user:e.user?.full_name||e.user?.email||session.cashier_name}));
 const deposits:CashupDeposit[]=(dr.data??[]).map((d:any)=>({id:d.id,date:d.created_at,bank:d.bank_name,reference:d.reference,amount:n(d.amount),recorded_by:d.recorder?.full_name||d.recorder?.email||session.cashier_name,notes:d.notes}));
 return{session,sales,refunds,expenses,deposits};
}
export async function getCashupExportData(f:CashupFilters,sort:CashupSort):Promise<CashupExportData>{const first=await getCashupReport(f,1,100,sort),pages=Math.ceil(first.total/100),rest=pages>1?await Promise.all(Array.from({length:pages-1},(_,i)=>getCashupReport(f,i+2,100,sort))):[],rows=[first.rows,...rest.map(r=>r.rows)].flat();validateCashupRows(rows);return{...first,rows,details:await Promise.all(rows.map(getCashupDetail)),generatedAt:new Date().toISOString()}}
