import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { InventoryReportExportData, InventoryReportRow, InventoryReportVariant } from '../types/inventoryReport';
import { downloadBlob } from './salesReportService';
import { formatInventoryPriceRange, inventoryStatusLabel } from '../utils/inventoryReportFormat';

const csvCell = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;
const money = (value: number) => `LKR ${value.toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const mainHeaders = ['Product Code', 'Product', 'Article', 'Category', 'Brand', 'Variants', 'Stock', 'Min Cost', 'Max Cost', 'Min Selling', 'Max Selling', 'Cost Value', 'Selling Value', 'Potential Profit', 'Status'];
const mainRow = (row: InventoryReportRow): Array<string | number> => [row.product_code, row.product_name, row.item_article ?? '', row.category_name, row.brand_name, row.variant_count, row.total_stock, row.min_cost ?? '', row.max_cost ?? '', row.min_selling ?? '', row.max_selling ?? '', row.cost_value, row.selling_value, row.potential_profit, inventoryStatusLabel(row.stock_status)];
const variantHeaders = ['Product', 'Article', 'Size', 'Colour', 'Barcode', 'Stock', 'Cost Price', 'Selling Price', 'Cost Value', 'Selling Value', 'Status'];
const variantRow = (row: InventoryReportVariant): Array<string | number> => [row.product_name, row.item_article ?? '', row.size, row.color, row.barcode_number ?? '', row.stock_quantity, row.cost_price ?? '', row.selling_price ?? '', row.cost_value ?? '', row.selling_value ?? '', inventoryStatusLabel(row.stock_status)];

export function exportInventoryReportCsv(data: InventoryReportExportData) { const csv = [mainHeaders, ...data.rows.map(mainRow)].map((row) => row.map(csvCell).join(',')).join('\r\n'); downloadBlob('inventory-report.csv', `\ufeff${csv}`, 'text/csv;charset=utf-8'); }
export function exportInventoryVariantCsv(data: InventoryReportExportData) { const csv = [variantHeaders, ...data.variants.map(variantRow)].map((row) => row.map(csvCell).join(',')).join('\r\n'); downloadBlob('inventory-variants.csv', `\ufeff${csv}`, 'text/csv;charset=utf-8'); }

const xmlText = (value: unknown) => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const sheet = (name: string, rows: Array<Array<string | number>>) => `<Worksheet ss:Name="${name}"><Table>${rows.map((row) => `<Row>${row.map((value) => `<Cell><Data ss:Type="${typeof value === 'number' ? 'Number' : 'String'}">${xmlText(value)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet>`;
export function exportInventoryReportExcel(data: InventoryReportExportData) { const xml = `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${sheet('Inventory Summary', [mainHeaders, ...data.rows.map(mainRow)])}${sheet('Variant Inventory', [variantHeaders, ...data.variants.map(variantRow)])}</Workbook>`; downloadBlob('inventory-report.xls', xml, 'application/vnd.ms-excel'); }

function pdfHeader(doc: jsPDF, generatedAt: string, detailed = false) { const width = doc.internal.pageSize.getWidth(); doc.setFillColor(5, 44, 36); doc.rect(0, 0, width, 27, 'F'); doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.setFontSize(15); doc.text('SHOE GALLERY', 12, 10); doc.setFontSize(11); doc.text(detailed ? 'Detailed Inventory Report' : 'Inventory Report', width - 12, 10, { align: 'right' }); doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.text(`Generated: ${new Date(generatedAt).toLocaleString()}`, width - 12, 18, { align: 'right' }); }
export function downloadInventoryReportPdf(data: InventoryReportExportData) { const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4', compress: true }); pdfHeader(doc, data.generatedAt); const s = data.summary; autoTable(doc, { startY: 32, theme: 'grid', margin: { left: 7, right: 7 }, head: [['Products', 'Variants', 'Total Stock', 'Cost Value', 'Selling Value', 'Potential Profit', 'Low Stock', 'Out of Stock']], body: [[s.total_products, s.total_variants, s.total_stock, money(s.cost_value), money(s.selling_value), money(s.potential_profit), s.low_stock_variants, s.out_of_stock_variants]], styles: { fontSize: 7, cellPadding: 1.7 }, headStyles: { fillColor: [5, 44, 36] } }); const y = ((doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 45) + 5; autoTable(doc, { startY: y, theme: 'grid', margin: { left: 5, right: 5, bottom: 12 }, head: [['Product', 'Article', 'Category', 'Brand', 'Variants', 'Stock', 'Cost Price', 'Selling Price', 'Cost Value', 'Selling Value', 'Status']], body: data.rows.map((row) => [row.product_name, row.item_article || '—', row.category_name, row.brand_name, row.variant_count, row.total_stock, formatInventoryPriceRange(row.min_cost, row.max_cost), formatInventoryPriceRange(row.min_selling, row.max_selling), money(row.cost_value), money(row.selling_value), inventoryStatusLabel(row.stock_status)]), styles: { fontSize: 6.5, cellPadding: 1.2 }, headStyles: { fillColor: [5, 44, 36] }, alternateRowStyles: { fillColor: [241, 245, 249] } }); doc.save('inventory-report.pdf'); }
export function downloadDetailedInventoryReportPdf(data: InventoryReportExportData) { const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4', compress: true }); pdfHeader(doc, data.generatedAt, true); let y = 33; for (const product of data.rows) { if (y > 170) { doc.addPage(); pdfHeader(doc, data.generatedAt, true); y = 33; } doc.setTextColor(15, 23, 42); doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.text(`${product.product_name} · ${product.item_article || product.product_code}`, 8, y); const variants = data.variants.filter((variant) => variant.product_id === product.product_id); autoTable(doc, { startY: y + 2, theme: 'grid', margin: { left: 8, right: 8, bottom: 10 }, head: [['Size', 'Colour', 'Barcode', 'Stock', 'Cost', 'Selling', 'Cost Value', 'Selling Value', 'Status']], body: variants.map((row) => [row.size, row.color, row.barcode_number || '—', row.stock_quantity, row.cost_price === null ? 'Missing' : money(row.cost_price), row.selling_price === null ? 'Missing' : money(row.selling_price), row.cost_value === null ? '—' : money(row.cost_value), row.selling_value === null ? '—' : money(row.selling_value), inventoryStatusLabel(row.stock_status)]), styles: { fontSize: 6.5, cellPadding: 1.2 }, headStyles: { fillColor: [5, 44, 36] }, pageBreak: 'avoid' }); y = ((doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 10) + 7; } doc.save('inventory-report-detailed.pdf'); }
