import { supabase } from './supabase';
import type { DailyProfit, ProfitDimension, ProfitExportData, ProfitFilters, ProfitInvoiceRow, ProfitItem, ProfitOptions, ProfitPageSize, ProfitReportResult, ProfitSort, ProfitSummary, ProfitTrendPoint } from '../types/profitReport';
import { validateProfitRows } from '../utils/profitReportValidation';
const n = (v: unknown) => Number(v ?? 0), nn = (v: unknown) => v == null ? null : Number(v);
const filtersJson = (f: ProfitFilters) => ({ ...f, startDate: f.startDate || '', endDate: f.endDate || '' });
function normDim(x: any): ProfitDimension { return { ...x, quantity: n(x.quantity), revenue: n(x.revenue), cogs: nn(x.cogs), gross_product_profit: nn(x.gross_product_profit), card_processing_fees: n(x.card_processing_fees), profit: nn(x.profit), margin: n(x.margin) }; }
function normalize(v: unknown): ProfitReportResult { const x = (v ?? {}) as any; const rows: ProfitInvoiceRow[] = (x.rows ?? []).map((r: any) => ({ ...r, item_count: n(r.item_count), quantity: n(r.quantity), gross_sales: n(r.gross_sales), discount: n(r.discount), net_sales: n(r.net_sales), cogs: nn(r.cogs), gross_product_profit: nn(r.gross_product_profit), card_processing_fee: n(r.card_processing_fee), profit: nn(r.profit), margin: n(r.margin) })); const z = x.summary ?? {}; const summary: ProfitSummary = { net_revenue: n(z.net_revenue), cogs: nn(z.cogs), gross_profit: nn(z.gross_profit), gross_product_profit: nn(z.gross_product_profit), card_processing_fees: n(z.card_processing_fees), net_profit: nn(z.net_profit), profit_margin: n(z.profit_margin), discounts: n(z.discounts), return_value: n(z.return_value), units_sold: n(z.units_sold), completed_sales: n(z.completed_sales), missing_cost_items: n(z.missing_cost_items) }; validateProfitRows(rows, summary); const daily: DailyProfit[] = (x.daily ?? []).map((d: any) => ({ ...d, invoices: n(d.invoices), units: n(d.units), revenue: n(d.revenue), discount: n(d.discount), returns: n(d.returns), cogs: nn(d.cogs), gross_product_profit: nn(d.gross_product_profit), card_processing_fees: n(d.card_processing_fees), profit: nn(d.profit), margin: n(d.margin) })); const trend: ProfitTrendPoint[] = (x.trend ?? []).map((d: any) => ({ ...d, revenue: n(d.revenue), cogs: n(d.cogs), profit: n(d.profit) })); return { rows, total: n(x.total), summary, products: (x.products ?? []).map(normDim), variants: (x.variants ?? []).map(normDim), categories: (x.categories ?? []).map(normDim), brands: (x.brands ?? []).map(normDim), daily, trend }; }
export async function getProfitReport(f: ProfitFilters, page = 1, size: ProfitPageSize = 25, sort: ProfitSort = 'newest') { if (f.startDate && f.endDate && f.startDate > f.endDate)
    throw new Error('From date cannot be after To date.'); const { data, error } = await supabase.rpc('get_profit_report', { p_filters: filtersJson(f), p_page: page, p_page_size: size, p_sort: sort }); if (error)
    throw error; return normalize(data); }
export async function getProfitOptions(): Promise<ProfitOptions> { const [c, b, p, u, m] = await Promise.all([supabase.from('categories').select('id,name').order('name'), supabase.from('brands').select('id,name').order('name'), supabase.from('products').select('id,name').order('name'), supabase.from('profiles').select('id,full_name,email').order('full_name'), supabase.from('sales').select('payment_method').not('payment_method', 'is', null)]); for (const x of [c, b, p, u, m])
    if (x.error)
        throw x.error; return { categories: c.data ?? [], brands: b.data ?? [], products: p.data ?? [], cashiers: (u.data ?? []).map(x => ({ id: x.id, name: x.full_name || x.email || 'Unknown' })), paymentMethods: [...new Set((m.data ?? []).map(x => x.payment_method).filter(Boolean))].sort() }; }
export async function getProfitItems(f: ProfitFilters, saleId?: string): Promise<ProfitItem[]> { const { data, error } = await supabase.rpc('get_profit_report_items', { p_filters: filtersJson(f), p_sale_id: saleId || null }); if (error)
    throw error; return ((data ?? []) as any[]).map(i => ({ ...i, quantity: n(i.quantity), selling_price: n(i.selling_price), discount: n(i.discount), returned_value: n(i.returned_value), net_revenue: n(i.net_revenue), unit_cost: nn(i.unit_cost), total_cost: nn(i.total_cost), gross_product_profit: nn(i.gross_product_profit), card_processing_fee: n(i.card_processing_fee), profit: nn(i.profit), margin: n(i.margin) })); }
export async function getProfitExportData(f: ProfitFilters, sort: ProfitSort): Promise<ProfitExportData> { const first = await getProfitReport(f, 1, 100, sort), pages = Math.ceil(first.total / 100), rest = pages > 1 ? await Promise.all(Array.from({ length: pages - 1 }, (_, i) => getProfitReport(f, i + 2, 100, sort))) : []; const rows = [first.rows, ...rest.map(r => r.rows)].flat(); validateProfitRows(rows, first.summary); return { ...first, rows, items: await getProfitItems(f), generatedAt: new Date().toISOString() }; }
