import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { SalesReportData, SalesReportFilters } from '../types/salesReport';

const C={navy:[15,23,42] as [number,number,number],blue:[14,165,233] as [number,number,number],slate:[71,85,105] as [number,number,number],line:[203,213,225] as [number,number,number],pale:[241,245,249] as [number,number,number]};
const rs=(value:number|null|undefined)=>value==null?'Not available':`Rs. ${Number(value).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const text=(value:unknown)=>value==null?'—':String(value);
const uniqueBy=<T,>(rows:T[],key:(row:T)=>string)=>[...new Map(rows.map(row=>[key(row),row])).values()];
const newestFirst=(left:string,right:string)=>(Date.parse(right)||0)-(Date.parse(left)||0);

export async function downloadSalesReportPdf(data:SalesReportData,filters:SalesReportFilters,generatedBy:string){
 // Defensive de-duplication before any tables are generated.
 data.invoices=uniqueBy(data.invoices,x=>x.id).sort((a,b)=>newestFirst(a.created_at,b.created_at));
 data.invoices.forEach(invoice=>{invoice.items=uniqueBy(invoice.items??[],item=>item.id)});
 data.payments=uniqueBy(data.payments,x=>x.id).sort((a,b)=>newestFirst(a.payment_date,b.payment_date));
 data.returns=uniqueBy(data.returns,x=>x.id).sort((a,b)=>newestFirst(a.created_at,b.created_at));
 const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});
 const fileName=`sales-report-${filters.startDate}-to-${filters.endDate}.pdf`;
 const header=(title:string)=>{doc.setFillColor(...C.navy);doc.rect(0,0,doc.internal.pageSize.getWidth(),25,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text(data.store.store_name||'Shoe Gallery',12,10);doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text([data.store.address,data.store.phone,data.store.email].filter(Boolean).join('  |  ').slice(0,110),12,16);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(title,doc.internal.pageSize.getWidth()-12,11,{align:'right'});doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(`${filters.startDate} to ${filters.endDate}`,doc.internal.pageSize.getWidth()-12,17,{align:'right'});doc.setTextColor(...C.navy)};
 const footer=()=>{const page=doc.getCurrentPageInfo().pageNumber;const h=doc.internal.pageSize.getHeight();doc.setDrawColor(...C.line);doc.line(12,h-10,doc.internal.pageSize.getWidth()-12,h-10);doc.setFontSize(7);doc.setTextColor(...C.slate);doc.text(`Generated ${new Date(data.generated_at).toLocaleString()} by ${generatedBy}`,12,h-5);doc.text(`Page ${page}`,doc.internal.pageSize.getWidth()-12,h-5,{align:'right'})};
 const table=(head:string[],body:(string|number)[][],startY:number,opts:Record<string,unknown>={})=>autoTable(doc,{head:[head],body,startY,margin:{left:12,right:12,bottom:14},theme:'grid',styles:{font:'helvetica',fontSize:7.5,cellPadding:2,textColor:C.navy,lineColor:C.line,lineWidth:.15,overflow:'linebreak',valign:'middle'},headStyles:{fillColor:C.navy,textColor:[255,255,255],fontStyle:'bold',fontSize:7},alternateRowStyles:{fillColor:C.pale},didDrawPage:footer,...opts});
 const section=(title:string,y:number)=>{doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(...C.navy);doc.text(title,12,y);doc.setDrawColor(...C.blue);doc.setLineWidth(.7);doc.line(12,y+2,40,y+2)};
 header('Detailed Sales Report');doc.setFontSize(20);doc.setFont('helvetica','bold');doc.text('Sales Performance Report',12,38);doc.setFontSize(9);doc.setFont('helvetica','normal');doc.setTextColor(...C.slate);doc.text(`Reporting period: ${filters.startDate} to ${filters.endDate}`,12,45);
 section('Executive summary',57);const cards=[['NET SALES',rs(data.summary.net_sales)],['GROSS PROFIT',rs(data.summary.gross_profit)],['RECEIVED',rs(data.summary.amount_received)],['OUTSTANDING',rs(data.summary.outstanding_amount)],['INVOICES',text(data.summary.total_invoices)],['QUANTITY SOLD',text(data.summary.total_quantity_sold)],['RETURNS',rs(data.summary.returned_amount)],['PROFIT MARGIN',data.summary.gross_profit_margin==null?'Not available':`${Number(data.summary.gross_profit_margin).toFixed(2)}%`]];cards.forEach(([label,value],i)=>{const col=i%4,row=Math.floor(i/4),x=12+col*46.5,y=64+row*25;doc.setFillColor(...C.pale);doc.roundedRect(x,y,43.5,20,2,2,'F');doc.setFontSize(6.5);doc.setTextColor(...C.slate);doc.text(label,x+3,y+6);doc.setFontSize(10);doc.setFont('helvetica','bold');doc.setTextColor(...C.navy);doc.text(value,x+3,y+14,{maxWidth:38});doc.setFont('helvetica','normal')});
 section('Financial breakdown',120);table(['Metric','Amount','Metric','Amount'],[['Gross sales',rs(data.summary.gross_sales),'Cost of goods',rs(data.summary.cost_of_goods)],['Invoice discounts',rs(data.summary.invoice_discounts),'Gross profit',rs(data.summary.gross_profit)],['Item discounts',rs(data.summary.item_discounts),'Average invoice',rs(data.summary.average_invoice_value)],['Returned amount',rs(data.summary.returned_amount),'Inventory sales',rs(data.summary.inventory_sale_total)],['Net sales',rs(data.summary.net_sales),'Instant billing',rs(data.summary.instant_billing_total)],['Cash received',rs(data.summary.cash_sales),'Credit sales',rs(data.summary.credit_sales)],['Card received',rs(data.summary.card_sales),'Bank transfers',rs(data.summary.bank_transfer_sales)]],126,{columnStyles:{1:{halign:'right',fontStyle:'bold'},3:{halign:'right',fontStyle:'bold'}}});

 doc.addPage('a4','landscape');header('Detailed Invoices');table(['Invoice','Date','Customer','Cashier','Qty','Gross','Discount','Returns','Net','Cost','Profit','Paid','Due','Status'],data.invoices.map(x=>[x.invoice_number,new Date(x.created_at).toLocaleDateString(),x.customer_name,x.cashier_name,x.total_quantity,rs(x.gross_amount),rs(x.item_discount+x.invoice_discount),rs(x.returned_amount),rs(x.net_amount),rs(x.cost_of_goods),rs(x.gross_profit),rs(x.amount_paid),rs(x.outstanding),x.status]),31,{styles:{fontSize:6,cellPadding:1.3},columnStyles:{0:{cellWidth:22},1:{cellWidth:15},2:{cellWidth:23},3:{cellWidth:20},4:{cellWidth:9,halign:'right'},5:{cellWidth:19,halign:'right'},6:{cellWidth:18,halign:'right'},7:{cellWidth:17,halign:'right'},8:{cellWidth:19,halign:'right'},9:{cellWidth:18,halign:'right'},10:{cellWidth:18,halign:'right'},11:{cellWidth:18,halign:'right'},12:{cellWidth:18,halign:'right'},13:{cellWidth:16}}});

 const saleItems=data.invoices.flatMap(x=>x.items.map(i=>[x.invoice_number,i.product_name,i.barcode||'—',i.category||'—',[i.size,i.colour].filter(Boolean).join(' / ')||'—',i.item_type,i.quantity_sold,i.quantity_returned,i.net_quantity,rs(i.selling_price),rs(i.discount),rs(i.net_revenue),rs(i.cost_total),rs(i.profit)]));
 if(saleItems.length){doc.addPage('a4','landscape');header('Detailed Sale Items');table(['Invoice','Product','Barcode','Category','Variant','Type','Sold','Returned','Net Qty','Selling Price','Discount','Net Revenue','Cost','Profit'],saleItems,31,{styles:{fontSize:6,cellPadding:1.3},columnStyles:{0:{cellWidth:22},1:{cellWidth:30},2:{cellWidth:18},3:{cellWidth:18},4:{cellWidth:20},5:{cellWidth:17},6:{cellWidth:9,halign:'right'},7:{cellWidth:11,halign:'right'},8:{cellWidth:10,halign:'right'},9:{cellWidth:18,halign:'right'},10:{cellWidth:18,halign:'right'},11:{cellWidth:20,halign:'right'},12:{cellWidth:18,halign:'right'},13:{cellWidth:18,halign:'right'}}})}

 if(data.payments.length){doc.addPage('a4','portrait');header('Payments');table(['Invoice','Method','Date','Reference','Received By','Amount'],data.payments.map(p=>[p.invoice_number||'—',p.payment_method,new Date(p.payment_date).toLocaleString(),p.reference_number||'—',p.received_by_name||'—',rs(p.amount)]),31,{columnStyles:{5:{halign:'right',fontStyle:'bold'}}})}
 if(data.returns.length){doc.addPage('a4','portrait');header('Returns');table(['Invoice','Return No.','Date','Reason','Processed By','Refund'],data.returns.map(r=>[r.invoice_number||'—',r.return_number,new Date(r.created_at).toLocaleString(),r.reason||'—',r.processed_by||'—',rs(r.refund_amount)]),31,{columnStyles:{5:{halign:'right',fontStyle:'bold'}}})}
 doc.save(fileName);
}
