import { supabase } from './supabase'; import type { CompleteExchangePayload,CompleteReturnPayload,POSReturnCandidate,ReturnableSale,SalesReturnRecord } from '../types/salesReturn';
const returnSelect=`*,sale:sales!sales_returns_sale_id_fkey(invoice_number,created_at,total_amount,payment_method,status),replacement_sale:sales!sales_returns_replacement_sale_id_fkey(invoice_number,created_at,total_amount,status),customer:customers(name,phone),sales_return_items(*),sale_refunds(*)`;
export async function getSalesReturns(filters:{search?:string;type?:string;status?:string;from?:string;to?:string;page:number;pageSize:number}){let q=supabase.from('sales_returns').select(returnSelect,{count:'exact'}).order('return_date',{ascending:false});if(filters.search)q=q.or(`return_number.ilike.%${filters.search}%`);if(filters.type)q=q.eq('return_type',filters.type);if(filters.status)q=q.eq('status',filters.status);if(filters.from)q=q.gte('return_date',`${filters.from}T00:00:00`);if(filters.to)q=q.lt('return_date',`${filters.to}T23:59:59.999`);const from=(filters.page-1)*filters.pageSize;const {data,error,count}=await q.range(from,from+filters.pageSize-1);if(error)throw error;return{rows:(data??[]) as unknown as SalesReturnRecord[],count:count??0}}
export async function getSalesReturn(id:string){const {data,error}=await supabase.from('sales_returns').select(returnSelect).eq('id',id).single();if(error)throw error;return data as unknown as SalesReturnRecord}
export async function searchReturnableSales(search:string){let q=supabase.from('sales').select(`*,customer:customers(name,phone),cashier:profiles(full_name,email),sale_items(*,variant:product_variants(id,barcode_number,size,color,stock_quantity,selling_price,product:products(name,item_article)))`).in('status',['completed','partially_returned']).order('created_at',{ascending:false}).limit(20);if(search)q=q.or(`invoice_number.ilike.%${search}%`);const {data,error}=await q;if(error)throw error;const sales=(data??[]) as unknown as ReturnableSale[];const ids=sales.flatMap(s=>s.sale_items.map(i=>i.id));const returned=new Map<string,number>();if(ids.length){const {data:ri,error:e}=await supabase.from('sales_return_items').select('sale_item_id,quantity_returned,sales_returns!inner(status)').in('sale_item_id',ids).eq('sales_returns.status','completed');if(e)throw e;for(const r of ri??[])returned.set(r.sale_item_id,(returned.get(r.sale_item_id)??0)+Number(r.quantity_returned))}return sales.map(s=>({...s,sale_items:s.sale_items.map(i=>({...i,previously_returned:returned.get(i.id)??0,remaining_quantity:i.quantity-(returned.get(i.id)??0)}))})).filter(s=>s.sale_items.some(i=>i.remaining_quantity>0))}
export async function completeSalesReturn(payload:CompleteReturnPayload){const {data,error}=await supabase.rpc('complete_sales_return',{p_payload:payload});if(error)throw error;return data as string}
export async function completeProductExchange(payload:CompleteExchangePayload){const {data,error}=await supabase.rpc('complete_product_exchange',{p_payload:payload});if(error)throw error;return data as string}
export async function getSalesReturnsForSale(saleId:string){
  const base='id,return_number,return_type,return_date,status';
  const result=await supabase.from('sales_returns').select(base+',difference_type,difference_amount').eq('sale_id',saleId).order('return_date',{ascending:false});
  if(!result.error)return result.data??[];
  const missingExchangeColumns=result.error.message?.includes('difference_type')||result.error.message?.includes('difference_amount')||result.error.code==='42703';
  if(!missingExchangeColumns)throw result.error;
  const fallback=await supabase.from('sales_returns').select(base).eq('sale_id',saleId).order('return_date',{ascending:false});
  if(fallback.error)throw fallback.error;
  return(fallback.data??[]).map(row=>({...row,difference_type:null,difference_amount:0}));
}
export async function cancelSalesReturn(id:string,reason:string){const {error}=await supabase.rpc('cancel_sales_return',{p_return_id:id,p_reason:reason});if(error)throw error}
export async function getPOSReturnCandidates(barcode:string){const{data,error}=await supabase.rpc('get_pos_return_candidates',{p_barcode:barcode.trim()});if(error)throw error;return(data??[])as POSReturnCandidate[]}
