export type ProfitPreset='today'|'yesterday'|'last_7_days'|'this_month'|'last_month'|'this_year'|'all_time'|'custom';export type ProfitSort='newest'|'oldest'|'revenue_desc'|'cogs_desc'|'profit_desc'|'profit_asc'|'margin_desc';export type ProfitPageSize=25|50|100;
export interface ProfitFilters{startDate:string;endDate:string;search:string;categoryId:string;brandId:string;productId:string;paymentMethod:string;cashierId:string;profitStatus:string}
export interface ProfitInvoiceRow{sale_id:string;invoice_number:string;sale_date:string;customer_name:string;cashier_name:string;item_count:number;quantity:number;gross_sales:number;discount:number;net_sales:number;cogs:number|null;profit:number|null;margin:number;payment_method:string;status:string}
export interface ProfitSummary{net_revenue:number;cogs:number|null;gross_profit:number|null;profit_margin:number;discounts:number;return_value:number;units_sold:number;completed_sales:number;missing_cost_items:number}
export interface ProfitDimension{key:string;product_name?:string;article?:string|null;size?:string|null;colour?:string|null;barcode?:string|null;name?:string;quantity:number;revenue:number;cogs:number|null;profit:number|null;margin:number}
export interface DailyProfit{date:string;invoices:number;units:number;revenue:number;discount:number;returns:number;cogs:number|null;profit:number|null;margin:number}
export interface ProfitTrendPoint{date:string;revenue:number;cogs:number;profit:number}
export interface ProfitReportResult{rows:ProfitInvoiceRow[];total:number;summary:ProfitSummary;products:ProfitDimension[];variants:ProfitDimension[];categories:ProfitDimension[];brands:ProfitDimension[];daily:DailyProfit[];trend:ProfitTrendPoint[]}
export interface ProfitOptions{categories:Array<{id:string;name:string}>;brands:Array<{id:string;name:string}>;products:Array<{id:string;name:string}>;cashiers:Array<{id:string;name:string}>;paymentMethods:string[]}
export interface ProfitItem{sale_item_id:string;sale_id:string;invoice_number:string;product_name:string;article:string|null;size:string|null;colour:string|null;barcode:string|null;quantity:number;selling_price:number;discount:number;returned_value:number;net_revenue:number;unit_cost:number|null;total_cost:number|null;profit:number|null;margin:number}
export interface ProfitExportData extends ProfitReportResult{items:ProfitItem[];generatedAt:string}
