import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Plus, ScanBarcode } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import type { Product, ProductVariant, Supplier } from '../types';
import type { PurchaseItemInput, PurchasePayload } from '../types/purchase';
import { getSuppliers } from '../services/supplierService';
import { getAllProductVariants } from '../services/productService';
import { getPurchaseById, savePurchase } from '../services/purchaseService';
import { validatePurchase } from '../utils/purchaseValidation';
import { formatCurrency } from '../utils/format';
import { getErrorMessage } from '../utils/errors';
import { Alert, Button, Input, LoadingSpinner, PageHeader, Select, Textarea } from '../components/ui';
import { PurchaseItemRow } from '../components/purchases/PurchaseItemRow';

type Variant = ProductVariant & { product: Product };
const today = () => new Date().toISOString().slice(0,10);
export function CreatePurchase() {
  const { id }=useParams<{id:string}>(); const navigate=useNavigate();
  const [suppliers,setSuppliers]=useState<Supplier[]>([]); const [variants,setVariants]=useState<Variant[]>([]); const [loading,setLoading]=useState(true);
  const [supplierId,setSupplierId]=useState(''); const [invoice,setInvoice]=useState(''); const [date,setDate]=useState(today()); const [notes,setNotes]=useState('');
  const [items,setItems]=useState<PurchaseItemInput[]>([]); const [search,setSearch]=useState(''); const [selected,setSelected]=useState('');
  const [discount,setDiscount]=useState(0); const [additional,setAdditional]=useState(0); const [paid,setPaid]=useState(0); const [method,setMethod]=useState('');
  const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);

  useEffect(()=>{void (async()=>{try{const [s,v]=await Promise.all([getSuppliers(),getAllProductVariants()]);if(s.error)throw s.error;if(v.error)throw v.error;setSuppliers((s.data??[]) as Supplier[]);setVariants((v.data??[]) as unknown as Variant[]);if(id){const p=await getPurchaseById(id);if(p.status!=='draft')throw new Error('Only draft purchases can be edited.');setSupplierId(p.supplier_id);setInvoice(p.supplier_invoice_number??'');setDate(p.purchase_date);setNotes(p.notes??'');setDiscount(Number(p.discount_amount));setAdditional(Number(p.additional_cost));setPaid(Number(p.paid_amount));setMethod(p.payment_method??'');setItems(p.purchase_items.map(i=>({variant_id:i.variant_id,quantity:i.quantity,cost_price:Number(i.cost_price),selling_price:i.selling_price===null?null:Number(i.selling_price),line_discount:Number(i.line_discount),update_selling_price:i.update_selling_price})));}}catch(e){setError(getErrorMessage(e,'Unable to load purchase form.'));}finally{setLoading(false);}})();},[id]);
  const filtered=useMemo(()=>variants.filter(v=>`${v.product.name} ${v.product.item_number??v.product.code} ${v.product.item_article??''} ${v.barcode_number??''} ${v.size} ${v.color}`.toLowerCase().includes(search.toLowerCase())).slice(0,100),[variants,search]);
  const addVariant=(variantId:string)=>{const v=variants.find(x=>x.id===variantId);if(!v)return;setItems(current=>{const found=current.find(x=>x.variant_id===variantId);return found?current.map(x=>x.variant_id===variantId?{...x,quantity:x.quantity+1}:x):[...current,{variant_id:v.id,quantity:1,cost_price:Number(v.cost_price),selling_price:Number(v.selling_price),line_discount:0,update_selling_price:false}]});setSelected('');setSearch('');};
  const barcodeKey=(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key!=='Enter')return;e.preventDefault();const v=variants.find(x=>x.barcode_number?.toLowerCase()===search.trim().toLowerCase());if(v)addVariant(v.id);else setError('No product variant matches this barcode.');};
  const subtotal=items.reduce((s,i)=>s+i.quantity*i.cost_price,0); const lineDiscounts=items.reduce((s,i)=>s+i.line_discount,0); const total=Math.max(0,subtotal-lineDiscounts-discount+additional); const balance=Math.max(0,total-paid);
  const submit=async(status:'draft'|'completed')=>{const payload:PurchasePayload={id,supplier_id:supplierId,supplier_invoice_number:invoice,purchase_date:date,discount_amount:discount,additional_cost:additional,paid_amount:paid,payment_method:method,notes,status,items};const validation=validatePurchase(payload);if(validation){setError(validation);return;}setSaving(true);setError(null);try{const purchaseId=await savePurchase(payload);navigate(status==='draft'?'/purchases':`/purchases/${purchaseId}`);}catch(e){setError(getErrorMessage(e,'Purchase could not be saved.'));}finally{setSaving(false);}};
  if(loading)return <LoadingSpinner/>;
  return <div className="space-y-6"><PageHeader title={id?'Edit Draft Purchase':'Create Purchase'} description="Stock changes only when a purchase is completed." action={<Button variant="secondary" onClick={()=>navigate('/purchases')}><ArrowLeft size={17}/>Back</Button>}/>{error&&<Alert message={error}/>}<div className="glass-card grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4"><Select label="Supplier" value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><Input label="Supplier invoice number" value={invoice} onChange={e=>setInvoice(e.target.value)}/><Input label="Purchase date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Textarea label="Notes" rows={1} value={notes} onChange={e=>setNotes(e.target.value)}/></div>
  <div className="glass-card p-5"><div className="mb-4 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><ScanBarcode className="absolute left-3 top-3 text-dashboard-text-sub" size={18}/><Input className="pl-10" placeholder="Search name, code, article, or scan barcode" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={barcodeKey}/></div><Select className="md:min-w-80" value={selected} onChange={e=>{setSelected(e.target.value);addVariant(e.target.value);}}><option value="">Select matching variant</option>{filtered.map(v=><option key={v.id} value={v.id}>{v.product.name}{v.product.item_article?` · ${v.product.item_article}`:''} — {v.size}/{v.color} — Stock {v.stock_quantity}</option>)}</Select><Button type="button" disabled={!selected} onClick={()=>addVariant(selected)}><Plus size={17}/>Add</Button></div><div className="overflow-x-auto"><table className="w-full"><thead className="text-left text-xs uppercase text-dashboard-text-sub"><tr>{['Product','Size','Colour','Stock','Qty','Cost','Selling','Discount','Line total','Price update',''].map(x=><th key={x} className="px-3 py-2">{x}</th>)}</tr></thead><tbody>{items.map((item,index)=><PurchaseItemRow key={item.variant_id} item={item} variant={variants.find(v=>v.id===item.variant_id)!} onChange={next=>setItems(xs=>xs.map((x,i)=>i===index?next:x))} onRemove={()=>setItems(xs=>xs.filter((_,i)=>i!==index))}/>)}</tbody></table>{!items.length&&<p className="py-10 text-center text-dashboard-text-sub">Search or scan a product to add purchase items.</p>}</div></div>
  <div className="grid gap-6 lg:grid-cols-2"><div className="glass-card grid gap-4 p-5 sm:grid-cols-2"><Input label="Purchase discount" type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/><Input label="Additional cost" type="number" min="0" step="0.01" value={additional} onChange={e=>setAdditional(Number(e.target.value))}/><Input label="Paid amount" type="number" min="0" max={total} step="0.01" value={paid} onChange={e=>setPaid(Number(e.target.value))}/><Select label="Payment method" value={method} onChange={e=>setMethod(e.target.value)}><option value="">Select method</option>{['Cash','Card','Bank Transfer','Cheque','Other'].map(x=><option key={x}>{x}</option>)}</Select></div><div className="glass-card p-5"><dl className="space-y-2 text-sm">{[['Subtotal',subtotal],['Line discounts',lineDiscounts],['Purchase discount',discount],['Additional cost',additional],['Total',total],['Paid',paid],['Balance',balance]].map(([l,v])=><div key={String(l)} className="flex justify-between"><dt className="text-dashboard-text-sub">{l}</dt><dd className="font-semibold text-dashboard-text-primary">{formatCurrency(Number(v))}</dd></div>)}</dl><div className="mt-5 flex flex-wrap justify-end gap-3"><Button variant="secondary" disabled={saving} onClick={()=>submit('draft')}>Save Draft</Button><Button disabled={saving} onClick={()=>submit('completed')}>{saving?'Saving…':'Complete Purchase'}</Button></div></div></div></div>;
}
