import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { Download, Eye, FileSpreadsheet, FileText, Printer } from 'lucide-react';
import { Alert, Button, DataTable, LoadingSpinner, PageHeader, Pagination, Select } from '../components/ui';
import { InventoryReportFilters } from '../components/reports/InventoryReportFilters';
import { InventoryReportDetailModal } from '../components/reports/InventoryReportDetailModal';
import { InventoryStatusBadge } from '../components/reports/inventoryReportShared';
import { formatInventoryPriceRange, inventoryStatusLabel } from '../utils/inventoryReportFormat';
import { downloadDetailedInventoryReportPdf, downloadInventoryReportPdf, exportInventoryReportCsv, exportInventoryReportExcel, exportInventoryVariantCsv } from '../services/inventoryReportExport';
import { getInventoryReport, getInventoryReportExportData, getInventoryReportOptions } from '../services/inventoryReportService';
import type { InventoryReportExportData, InventoryReportFilters as Filters, InventoryReportOptions, InventoryReportPageSize, InventoryReportRow, InventoryReportSort, InventoryReportSummary } from '../types/inventoryReport';
import { formatCurrency } from '../utils/format';

const defaults = (): Filters => ({ search: '', categoryId: '', brandId: '', stockStatus: '' });
const emptyOptions: InventoryReportOptions = { categories: [], brands: [] };
export function InventoryReportPage() {
  const [draft, setDraft] = useState<Filters>(defaults); const [filters, setFilters] = useState<Filters>(defaults); const [options, setOptions] = useState<InventoryReportOptions>(emptyOptions);
  const [rows, setRows] = useState<InventoryReportRow[]>([]); const [summary, setSummary] = useState<InventoryReportSummary>(); const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState<InventoryReportPageSize>(25); const [sort, setSort] = useState<InventoryReportSort>('product_asc');
  const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false); const [error, setError] = useState<string>(); const [detail, setDetail] = useState<InventoryReportRow>(); const [printData, setPrintData] = useState<InventoryReportExportData>();
  useEffect(() => { void getInventoryReportOptions().then(setOptions).catch((reason) => { if (import.meta.env.DEV) console.error(reason); setError('Unable to load Inventory Report.'); }); }, []);
  const load = useCallback(async () => { setLoading(true); setError(undefined); try { const result = await getInventoryReport(filters, page, pageSize, sort); setRows(result.rows); setSummary(result.summary); setTotal(result.total); } catch (reason) { if (import.meta.env.DEV) console.error(reason); setError('Unable to load Inventory Report.'); } finally { setLoading(false); } }, [filters, page, pageSize, sort]);
  useEffect(() => { void load(); }, [load]);
  const apply = () => { setPage(1); setFilters(draft); }; const clear = () => { const value = defaults(); setDraft(value); setFilters(value); setSort('product_asc'); setPage(1); };
  const prepare = async (action: (data: InventoryReportExportData) => void) => { setExporting(true); setError(undefined); try { action(await getInventoryReportExportData(filters, sort)); } catch (reason) { if (import.meta.env.DEV) console.error(reason); setError('Unable to export Inventory Report.'); } finally { setExporting(false); } };
  const print = async () => { setExporting(true); try { const value = await getInventoryReportExportData(filters, sort); setPrintData(value); setTimeout(() => window.print(), 100); } catch (reason) { if (import.meta.env.DEV) console.error(reason); setError('Unable to print Inventory Report.'); } finally { setExporting(false); } };
  const pages = Math.max(1, Math.ceil(total / pageSize)); const first = total ? (page - 1) * pageSize + 1 : 0; const last = Math.min(page * pageSize, total);
  return <div className="inventory-report-page space-y-5"><PageHeader title="Inventory Report" description={`Current stock, valuation and variant breakdown · Generated ${new Date().toLocaleString()}`} action={<div className="flex flex-wrap gap-2 print-hidden"><Button variant="secondary" disabled={exporting} onClick={() => void prepare(exportInventoryReportCsv)}><Download size={16} />CSV</Button><Button variant="secondary" disabled={exporting} onClick={() => void prepare(exportInventoryVariantCsv)}><Download size={16} />Variant CSV</Button><Button variant="secondary" disabled={exporting} onClick={() => void prepare(exportInventoryReportExcel)}><FileSpreadsheet size={16} />Excel</Button><Button variant="secondary" disabled={exporting} onClick={() => void prepare(downloadInventoryReportPdf)}><FileText size={16} />PDF</Button><Button variant="secondary" disabled={exporting} onClick={() => void prepare(downloadDetailedInventoryReportPdf)}><FileText size={16} />Detailed PDF</Button><Button variant="secondary" disabled={exporting} onClick={() => void print()}><Printer size={16} />Print</Button></div>} />
    <InventoryReportFilters value={draft} options={options} onChange={setDraft} onApply={apply} onReset={clear} />
    {error && <div className="space-y-2"><Alert message={error} /><Button variant="secondary" onClick={() => void load()}>Retry</Button></div>}
    {loading ? <Skeleton /> : summary && <><SummaryCards summary={summary} /><IssueCard summary={summary} /></>}
    <section className="glass-card overflow-hidden"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-white/10 p-4 print-hidden"><div><h2 className="font-semibold text-dashboard-text-primary">Product Inventory</h2><p className="text-xs text-dashboard-text-sub">Showing {first}-{last} of {total.toLocaleString()} products</p></div><div className="flex flex-wrap gap-3"><Select label="Sort" value={sort} onChange={(event) => { setSort(event.target.value as InventoryReportSort); setPage(1); }}><option value="product_asc">Product A–Z</option><option value="product_desc">Product Z–A</option><option value="stock_desc">Stock high–low</option><option value="stock_asc">Stock low–high</option><option value="cost_value_desc">Cost value high–low</option><option value="cost_value_asc">Cost value low–high</option><option value="selling_value_desc">Selling value high–low</option><option value="selling_value_asc">Selling value low–high</option><option value="status_asc">Status</option></Select><Select label="Rows" value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value) as InventoryReportPageSize); setPage(1); }}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></Select></div></div>
      {loading ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : rows.length === 0 ? <div className="flex min-h-72 flex-col items-center justify-center gap-4 p-6"><p className="text-dashboard-text-sub">No inventory products found.</p><Button variant="secondary" onClick={clear}>Clear Filters</Button></div> : <InventoryTable rows={rows} onView={setDetail} />}
    </section>{!loading && total > 0 && <Pagination page={page} totalPages={pages} onPageChange={setPage} />}
    {detail && summary && <InventoryReportDetailModal product={detail} threshold={summary.low_stock_threshold} onClose={() => setDetail(undefined)} />}{printData && <InventoryPrintReport data={printData} />}
  </div>;
}
function SummaryCards({ summary: s }: { summary: InventoryReportSummary }) { const cards: Array<[string, string]> = [['Total Products', s.total_products.toLocaleString()], ['Total Variants', s.total_variants.toLocaleString()], ['Total Stock Units', `${s.total_stock.toLocaleString()} units`], ['Inventory Cost Value', formatCurrency(s.cost_value)], ['Inventory Selling Value', formatCurrency(s.selling_value)], ['Potential Gross Profit', formatCurrency(s.potential_profit)], ['Low Stock Variants', s.low_stock_variants.toLocaleString()], ['Out of Stock Variants', s.out_of_stock_variants.toLocaleString()]]; return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-8">{cards.map(([name, value]) => <div key={name} className="glass-card p-4"><p className="text-xs uppercase tracking-wide text-dashboard-text-label">{name}</p><p className="mt-2 text-lg font-bold text-dashboard-text-primary">{value}</p></div>)}</div>; }
function IssueCard({ summary: s }: { summary: InventoryReportSummary }) { if (!(s.missing_cost || s.missing_selling || s.missing_barcode || s.negative_stock)) return null; return <div className="glass-card border-amber-500/20 p-4"><p className="font-semibold text-amber-300">Inventory Issues</p><p className="mt-1 text-sm text-dashboard-text-sub">Missing cost: {s.missing_cost} · Missing selling price: {s.missing_selling} · Missing barcode: {s.missing_barcode} · Negative stock: {s.negative_stock}</p></div>; }
function Skeleton() { return <div className="grid animate-pulse gap-3 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-8">{Array.from({ length: 8 }, (_, i) => <div key={i} className="glass-card h-24 bg-white/[.04]" />)}</div>; }
function InventoryTable({ rows, onView }: { rows: InventoryReportRow[]; onView: (row: InventoryReportRow) => void }) { const headers = ['Product Code', 'Product', 'Article', 'Category', 'Brand', 'Variants', 'Total Stock', 'Cost Price', 'Selling Price', 'Cost Value', 'Selling Value', 'Status', 'Actions']; return <DataTable columns={headers.map((header, index) => ({ key: String(index), header }))} className="inventory-report-table">{rows.map((row) => <tr key={row.product_id} className="hover:bg-dashboard-hover"><Cell strong>{row.product_code}</Cell><Cell strong>{row.product_name}</Cell><Cell>{row.item_article || '—'}</Cell><Cell>{row.category_name}</Cell><Cell>{row.brand_name}</Cell><Cell>{row.variant_count}</Cell><Cell strong>{row.total_stock}</Cell><Cell>{formatInventoryPriceRange(row.min_cost, row.max_cost)}</Cell><Cell>{formatInventoryPriceRange(row.min_selling, row.max_selling)}</Cell><Cell>{formatCurrency(row.cost_value)}</Cell><Cell>{formatCurrency(row.selling_value)}</Cell><Cell><InventoryStatusBadge status={row.stock_status} /></Cell><td className="sticky right-0 bg-[#061711] px-3 py-2 text-right"><Button size="sm" variant="secondary" onClick={() => onView(row)}><Eye size={15} />View</Button></td></tr>)}</DataTable>; }
function Cell({ children, strong = false }: { children: ReactNode; strong?: boolean }) { return <td className={`whitespace-nowrap px-4 py-3 text-sm ${strong ? 'font-semibold text-dashboard-text-primary' : 'text-dashboard-text-sub'}`}>{children}</td>; }
function InventoryPrintReport({ data }: { data: InventoryReportExportData }) { const s = data.summary; return <div className="report-print-area business-report-print-area inventory-report-print"><div className="report-header"><div><p className="report-eyebrow">SHOE GALLERY</p><h1>Inventory Report</h1><p className="report-subtitle">Current stock, valuation and variant breakdown</p></div><dl className="report-meta-grid"><div><dt>Generated</dt><dd>{new Date(data.generatedAt).toLocaleString()}</dd></div></dl></div><div className="report-kpi-grid">{[['Products', s.total_products], ['Variants', s.total_variants], ['Total Stock', s.total_stock], ['Cost Value', formatCurrency(s.cost_value)], ['Selling Value', formatCurrency(s.selling_value)], ['Potential Profit', formatCurrency(s.potential_profit)], ['Low Stock', s.low_stock_variants], ['Out of Stock', s.out_of_stock_variants]].map(([name, value]) => <div className="report-kpi" key={String(name)}><span className="report-kpi-label">{name}</span><span className="report-kpi-value">{value}</span></div>)}</div><table className="report-table"><thead><tr>{['Product', 'Article', 'Category', 'Brand', 'Variants', 'Stock', 'Cost Price', 'Selling Price', 'Cost Value', 'Selling Value', 'Status'].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{data.rows.map((row) => <tr key={row.product_id}><td>{row.product_name}</td><td>{row.item_article || '—'}</td><td>{row.category_name}</td><td>{row.brand_name}</td><td>{row.variant_count}</td><td>{row.total_stock}</td><td>{formatInventoryPriceRange(row.min_cost, row.max_cost)}</td><td>{formatInventoryPriceRange(row.min_selling, row.max_selling)}</td><td>{formatCurrency(row.cost_value)}</td><td>{formatCurrency(row.selling_value)}</td><td>{inventoryStatusLabel(row.stock_status)}</td></tr>)}</tbody></table></div>; }
