import { useCallback, useEffect, useState } from 'react';
import { Download, Eye, FileSpreadsheet, FileText, Printer } from 'lucide-react';
import { Alert, Button, DataTable, LoadingSpinner, PageHeader, Pagination, Select } from '../components/ui';
import { PurchaseReportFilters } from '../components/reports/PurchaseReportFilters';
import { PurchaseReportDetailModal } from '../components/reports/PurchaseReportDetailModal';
import { downloadPurchaseReportPdf, exportPurchaseReportCsv, exportPurchaseReportExcel } from '../services/purchaseReportExport';
import { getPurchaseReport, getPurchaseReportExportData, getPurchaseReportOptions } from '../services/purchaseReportService';
import type { PurchaseReportExportData, PurchaseReportFilters as Filters, PurchaseReportOptions, PurchaseReportPageSize, PurchaseReportPreset, PurchaseReportRow, PurchaseReportSort, PurchaseReportSummary } from '../types/purchaseReport';
import { getErrorMessage } from '../utils/errors';
import { formatCurrency, formatDate } from '../utils/format';
import { displayPurchaseDateRange, purchasePresetDates } from '../utils/purchaseReportDates';

const defaults = (): Filters => ({ ...purchasePresetDates('this_month'), search: '', supplierId: '', paymentStatus: '', purchaseStatus: '', paymentMethod: '' });
const emptyOptions: PurchaseReportOptions = { suppliers: [], paymentMethods: [] };
const title = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());

export function PurchaseReportPage() {
  const [preset, setPreset] = useState<PurchaseReportPreset>('this_month'); const [draft, setDraft] = useState<Filters>(defaults); const [filters, setFilters] = useState<Filters>(defaults);
  const [options, setOptions] = useState<PurchaseReportOptions>(emptyOptions); const [rows, setRows] = useState<PurchaseReportRow[]>([]); const [summary, setSummary] = useState<PurchaseReportSummary>();
  const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState<PurchaseReportPageSize>(25); const [sort, setSort] = useState<PurchaseReportSort>('newest');
  const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false); const [error, setError] = useState<string>(); const [detailId, setDetailId] = useState<string>(); const [printData, setPrintData] = useState<PurchaseReportExportData>();

  useEffect(() => { void getPurchaseReportOptions().then(setOptions).catch((reason) => setError(getErrorMessage(reason, 'Unable to load Purchase Report.'))); }, []);
  const load = useCallback(async () => { setLoading(true); setError(undefined); try { const result = await getPurchaseReport(filters, page, pageSize, sort); setRows(result.rows); setSummary(result.summary); setTotal(result.total); } catch (reason) { if (import.meta.env.DEV) console.error(reason); setError('Unable to load Purchase Report.'); } finally { setLoading(false); } }, [filters, page, pageSize, sort]);
  useEffect(() => { void load(); }, [load]);
  const choosePreset = (next: PurchaseReportPreset) => { setPreset(next); if (next !== 'custom') setDraft((current) => ({ ...current, ...purchasePresetDates(next) })); };
  const apply = () => { setPage(1); setFilters(draft); };
  const clear = () => { const next = defaults(); setPreset('this_month'); setDraft(next); setFilters(next); setSort('newest'); setPage(1); };
  const prepare = async (action: (data: PurchaseReportExportData) => void) => { setExporting(true); setError(undefined); try { action(await getPurchaseReportExportData(filters, sort)); } catch (reason) { if (import.meta.env.DEV) console.error(reason); setError('Unable to export Purchase Report.'); } finally { setExporting(false); } };
  const print = async () => { setExporting(true); try { const data = await getPurchaseReportExportData(filters, sort); setPrintData(data); setTimeout(() => window.print(), 100); } catch (reason) { if (import.meta.env.DEV) console.error(reason); setError('Unable to print Purchase Report.'); } finally { setExporting(false); } };
  const range = displayPurchaseDateRange(filters.startDate, filters.endDate); const totalPages = Math.max(1, Math.ceil(total / pageSize)); const first = total ? (page - 1) * pageSize + 1 : 0; const last = Math.min(page * pageSize, total);

  return <div className="purchase-report-page space-y-5">
    <PageHeader title="Purchase Report" description={`Complete purchase and supplier history · ${range}`} action={<div className="flex flex-wrap gap-2 print-hidden"><Button variant="secondary" disabled={exporting} onClick={() => void prepare(exportPurchaseReportCsv)}><Download size={16} />Export CSV</Button><Button variant="secondary" disabled={exporting} onClick={() => void prepare(exportPurchaseReportExcel)}><FileSpreadsheet size={16} />Export Excel</Button><Button variant="secondary" disabled={exporting} onClick={() => void prepare((data) => downloadPurchaseReportPdf(data, filters))}><FileText size={16} />Export PDF</Button><Button variant="secondary" disabled={exporting} onClick={() => void print()}><Printer size={16} />Print</Button></div>} />
    <PurchaseReportFilters value={draft} preset={preset} options={options} onPreset={choosePreset} onChange={(value) => { setDraft(value); setPreset('custom'); }} onApply={apply} onReset={clear} />
    {error && <div className="space-y-2"><Alert message={error} /><Button variant="secondary" onClick={() => void load()}>Retry</Button></div>}
    {loading ? <ReportSkeleton /> : summary && <SummaryCards summary={summary} />}
    <section className="glass-card overflow-hidden">
      <div className="flex flex-wrap items-end justify-between gap-3 border-b border-white/10 p-4 print-hidden"><div><h2 className="font-semibold text-dashboard-text-primary">Purchases</h2><p className="text-xs text-dashboard-text-sub">Showing {first}-{last} of {total.toLocaleString()} purchases</p></div><div className="flex flex-wrap gap-3"><Select label="Sort" value={sort} onChange={(event) => { setSort(event.target.value as PurchaseReportSort); setPage(1); }}><option value="newest">Date: newest first</option><option value="oldest">Date: oldest first</option><option value="number_asc">Purchase number A–Z</option><option value="number_desc">Purchase number Z–A</option><option value="supplier_asc">Supplier A–Z</option><option value="total_desc">Total high–low</option><option value="total_asc">Total low–high</option><option value="balance_desc">Balance high–low</option><option value="balance_asc">Balance low–high</option></Select><Select label="Rows" value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value) as PurchaseReportPageSize); setPage(1); }}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></Select></div></div>
      {loading ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : rows.length === 0 ? <div className="flex min-h-72 flex-col items-center justify-center gap-4 p-6 text-center"><p className="text-dashboard-text-sub">No purchases found for this period.</p><Button variant="secondary" onClick={clear}>Clear Filters</Button></div> : <PurchaseTable rows={rows} onView={setDetailId} />}
    </section>
    {!loading && total > 0 && <Pagination page={page} totalPages={totalPages} onPageChange={setPage} />}
    {detailId && <PurchaseReportDetailModal purchaseId={detailId} onClose={() => setDetailId(undefined)} />}
    {printData && <PurchasePrintReport data={printData} range={range} />}
  </div>;
}

function SummaryCards({ summary }: { summary: PurchaseReportSummary }) { const cards: Array<[string, string]> = [['Total Purchase Value', formatCurrency(summary.total_purchase_value)], ['Total Purchases', summary.total_purchases.toLocaleString()], ['Total Quantity Purchased', summary.total_quantity.toLocaleString()], ['Total Paid', formatCurrency(summary.total_paid)], ['Outstanding', formatCurrency(summary.total_outstanding)], ['Total Discounts', formatCurrency(summary.total_discounts)]]; return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{cards.map(([name, value]) => <div key={name} className="glass-card p-4"><p className="text-xs uppercase tracking-wide text-dashboard-text-label">{name}</p><p className="mt-2 text-xl font-bold text-dashboard-text-primary">{value}</p></div>)}</div>; }
function ReportSkeleton() { return <div className="grid animate-pulse gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{Array.from({ length: 6 }, (_, index) => <div key={index} className="glass-card h-24 bg-white/[.04]" />)}</div>; }
function Badge({ value }: { value: string }) { const tone = value === 'paid' || value === 'completed' ? 'bg-emerald-500/15 text-emerald-300' : value === 'partial' || value === 'draft' ? 'bg-amber-500/15 text-amber-300' : value === 'cancelled' ? 'bg-red-500/15 text-red-300' : 'bg-slate-500/15 text-slate-300'; return <span className={`rounded-full px-2 py-1 text-xs font-semibold ${tone}`}>{title(value)}</span>; }
function PurchaseTable({ rows, onView }: { rows: PurchaseReportRow[]; onView: (id: string) => void }) { const columns = ['Purchase No', 'Date', 'Supplier', 'Supplier Invoice', 'Items', 'Qty', 'Subtotal', 'Discount', 'Additional Cost', 'Total', 'Paid', 'Balance', 'Payment Status', 'Status', 'Actions'].map((header, index) => ({ key: `${index}`, header })); return <DataTable columns={columns} className="purchase-report-table">{rows.map((row) => <tr key={row.purchase_id} className="hover:bg-dashboard-hover"><Cell strong>{row.purchase_number}</Cell><Cell>{formatDate(row.purchase_date)}</Cell><Cell strong>{row.supplier_name}</Cell><Cell>{row.supplier_invoice_number || '—'}</Cell><Cell>{row.item_lines}</Cell><Cell>{row.total_quantity}</Cell><Cell>{formatCurrency(row.subtotal)}</Cell><Cell>{formatCurrency(row.discount_amount)}</Cell><Cell>{formatCurrency(row.additional_cost)}</Cell><Cell strong>{formatCurrency(row.total_amount)}</Cell><Cell>{formatCurrency(row.paid_amount)}</Cell><Cell>{formatCurrency(row.balance_amount)}</Cell><Cell><Badge value={row.payment_status} /></Cell><Cell><Badge value={row.status} /></Cell><td className="sticky right-0 bg-[#061711] px-3 py-2 text-right"><Button size="sm" variant="secondary" onClick={() => onView(row.purchase_id)}><Eye size={15} />View</Button></td></tr>)}</DataTable>; }
function Cell({ children, strong = false }: { children: React.ReactNode; strong?: boolean }) { return <td className={`whitespace-nowrap px-4 py-3 text-sm ${strong ? 'font-semibold text-dashboard-text-primary' : 'text-dashboard-text-sub'}`}>{children}</td>; }
function PurchasePrintReport({ data, range }: { data: PurchaseReportExportData; range: string }) { return <div className="report-print-area business-report-print-area purchase-report-print"><div className="report-header"><div><p className="report-eyebrow">SHOE GALLERY</p><h1>Purchase Report</h1><p className="report-subtitle">Complete purchase and supplier history</p></div><dl className="report-meta-grid"><div><dt>Date Range</dt><dd>{range}</dd></div><div><dt>Generated</dt><dd>{new Date(data.generatedAt).toLocaleString()}</dd></div></dl></div><div className="report-kpi-grid">{[['Purchase Value', formatCurrency(data.summary.total_purchase_value)], ['Purchases', data.summary.total_purchases], ['Quantity', data.summary.total_quantity], ['Paid', formatCurrency(data.summary.total_paid)], ['Outstanding', formatCurrency(data.summary.total_outstanding)], ['Discounts', formatCurrency(data.summary.total_discounts)]].map(([name, value]) => <div className="report-kpi" key={String(name)}><span className="report-kpi-label">{name}</span><span className="report-kpi-value">{value}</span></div>)}</div><table className="report-table"><thead><tr>{['Purchase No', 'Date', 'Supplier', 'Supplier Invoice', 'Qty', 'Subtotal', 'Discount', 'Total', 'Paid', 'Balance', 'Payment', 'Status'].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{data.rows.map((row) => <tr key={row.purchase_id}><td>{row.purchase_number}</td><td>{formatDate(row.purchase_date)}</td><td>{row.supplier_name}</td><td>{row.supplier_invoice_number || '—'}</td><td>{row.total_quantity}</td><td>{formatCurrency(row.subtotal)}</td><td>{formatCurrency(row.discount_amount)}</td><td>{formatCurrency(row.total_amount)}</td><td>{formatCurrency(row.paid_amount)}</td><td>{formatCurrency(row.balance_amount)}</td><td>{title(row.payment_status)}</td><td>{title(row.status)}</td></tr>)}</tbody></table></div>; }
