import { useCallback,useEffect,useRef,useState,type CSSProperties } from 'react'; import { ArrowLeft,Printer,RotateCcw } from 'lucide-react'; import { Link,useLocation,useParams } from 'react-router-dom'; import type { SaleWithRelations } from '../services/salesService'; import * as salesService from '../services/salesService'; import * as settingsService from '../services/settingsService'; import type { StoreSettings } from '../types'; import { getErrorMessage } from '../utils/errors'; import { formatCurrency,formatDateTime } from '../utils/format'; import { Alert,Button,LoadingSpinner,PageHeader } from '../components/ui'; import { ThermalReceipt } from '../components/thermal/ThermalReceipt';
export function SaleDetail(){const{id}=useParams<{id:string}>();const location=useLocation();const[sale,setSale]=useState<SaleWithRelations|null>(null);const[settings,setSettings]=useState<StoreSettings|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const printed=useRef(false);const receiptRef=useRef<HTMLDivElement>(null);const pageStyleRef=useRef<HTMLStyleElement|null>(null);
const load=useCallback(async()=>{if(!id)return;setLoading(true);const[s,t]=await Promise.all([salesService.getSaleById(id),settingsService.getStoreSettings()]);if(s.error)setError(getErrorMessage(s.error));else setSale(s.data as SaleWithRelations|null);if(!t.error)setSettings(t.data as StoreSettings|null);setLoading(false)},[id]);useEffect(()=>{void load()},[load]);
useEffect(()=>{document.documentElement.classList.add('thermal-print-mode');return()=>{document.documentElement.classList.remove('thermal-print-mode');pageStyleRef.current?.remove();pageStyleRef.current=null}},[]);
const sizeReceiptPage=useCallback(()=>{const node=receiptRef.current;if(!node)return;const paperWidthMm=Number(settings?.receipt_paper_width_mm??80);const heightMm=Math.ceil((node.getBoundingClientRect().height*25.4/96+.5)*10)/10;let style=pageStyleRef.current;if(!style){style=document.createElement('style');style.dataset.thermalPageSize='true';document.head.appendChild(style);pageStyleRef.current=style}style.textContent=`@media print{@page{size:${paperWidthMm}mm ${heightMm}mm;margin:0}}`},[settings]);
useEffect(()=>{window.addEventListener('beforeprint',sizeReceiptPage);return()=>window.removeEventListener('beforeprint',sizeReceiptPage)},[sizeReceiptPage]);
const printReceipt=useCallback(async()=>{await document.fonts?.ready;await Promise.all(Array.from(receiptRef.current?.querySelectorAll('img')??[]).map(image=>image.complete?Promise.resolve():new Promise<void>(resolve=>{image.addEventListener('load',()=>resolve(),{once:true});image.addEventListener('error',()=>resolve(),{once:true})})));sizeReceiptPage();window.focus();window.print()},[sizeReceiptPage]);
useEffect(()=>{if(loading||!sale||printed.current||new URLSearchParams(location.search).get('print')!=='1')return;printed.current=true;void printReceipt()},[loading,location.search,printReceipt,sale]);
const receiptStyle={'--receipt-paper-width':`${Number(settings?.receipt_paper_width_mm??80)}mm`,'--receipt-left-padding':`${Number(settings?.receipt_left_padding_mm??4)}mm`,'--receipt-right-padding':`${Number(settings?.receipt_right_padding_mm??4)}mm`,'--receipt-top-padding':`${Number(settings?.receipt_top_padding_mm??2)}mm`,'--receipt-bottom-padding':`${Number(settings?.receipt_bottom_padding_mm??2)}mm`,'--receipt-font-size':`${Number(settings?.receipt_font_size_px??11)}px`} as CSSProperties;
if(loading)return <LoadingSpinner/>;if(!sale)return <Alert message={error||'Sale not found.'}/>;const width=Number(settings?.receipt_paper_width_mm??80);return <div className="space-y-6"><div className="print-hidden"><PageHeader title={sale.invoice_number||`Sale ${sale.id.slice(0,8)}`} description={`Invoice details and ${width}mm thermal receipt`} action={<div className="flex gap-2"><Link to="/sales"><Button variant="secondary"><ArrowLeft size={16}/>Back</Button></Link><Link to={`/returns/new?invoice=${encodeURIComponent(sale.invoice_number||'')}`}><Button variant="secondary"><RotateCcw size={16}/>Return / Exchange</Button></Link><Button onClick={()=>void printReceipt()}><Printer size={16}/>Print Receipt</Button></div>}/>{error&&<Alert message={error}/>}<section className="glass-card mx-auto max-w-3xl p-5"><div className="relative z-10 grid gap-3 text-sm sm:grid-cols-2"><p>Date: {formatDateTime(sale.created_at)}</p><p>Customer: {sale.customer?.name||'Walk-in Customer'}</p><p>Payment: {sale.payment_method.replaceAll('_',' ')}</p><p>Total: {formatCurrency(Number(sale.total_amount))}</p></div></section><p className="mt-3 text-center text-xs text-dashboard-text-sub">Print at 100% using {width}mm paper, margins None, and browser headers and footers Off.</p></div><div ref={receiptRef} className="thermal-preview thermal-print-area" style={receiptStyle}><ThermalReceipt sale={sale} settings={settings}/></div></div>}
