import { useCallback,useEffect,useMemo,useRef,useState } from 'react'; import { ArrowLeft,Printer,RotateCcw } from 'lucide-react'; import { Link,useLocation,useParams } from 'react-router-dom'; import type { SaleWithRelations } from '../services/salesService'; import * as salesService from '../services/salesService'; import * as settingsService from '../services/settingsService'; import type { StoreSettings } from '../types'; import { getErrorMessage } from '../utils/errors'; import { formatCurrency,formatDateTime } from '../utils/format'; import { Alert,Button,LoadingSpinner,PageHeader } from '../components/ui'; import { ThermalReceipt } from '../components/receipt/ThermalReceipt'; import { printReceipt } from '../services/receiptPrintService';
const testCounts=[1,5,10,20,30,50];
export function SaleDetail(){const{id}=useParams<{id:string}>();const location=useLocation();const[sale,setSale]=useState<SaleWithRelations|null>(null);const[settings,setSettings]=useState<StoreSettings|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[testCount,setTestCount]=useState<number|null>(null);const printed=useRef(false);
const load=useCallback(async()=>{if(!id)return;setLoading(true);const[s,t]=await Promise.all([salesService.getSaleById(id),settingsService.getStoreSettings()]);if(s.error)setError(getErrorMessage(s.error));else setSale(s.data as SaleWithRelations|null);if(!t.error)setSettings(t.data as StoreSettings|null);setLoading(false)},[id]);useEffect(()=>{void load()},[load]);
const displayItems=useMemo(()=>{if(!sale||!testCount||!sale.sale_items.length)return sale?.sale_items||[];return Array.from({length:testCount},(_,index)=>({...sale.sale_items[index%sale.sale_items.length],id:`thermal-test-${index}`}))},[sale,testCount]);
const receipt=useMemo(()=>sale?<ThermalReceipt sale={sale} items={displayItems} payments={sale.sale_payments||[]} customer={sale.customer} store={settings}/>:null,[displayItems,sale,settings]);
const handlePrint=useCallback(()=>{if(!receipt)return;try{printReceipt(receipt)}catch(e){setError(getErrorMessage(e,'Unable to open receipt print window.'))}},[receipt]);
useEffect(()=>{if(loading||!sale||printed.current||new URLSearchParams(location.search).get('print')!=='1')return;printed.current=true;handlePrint()},[handlePrint,loading,location.search,sale]);
if(loading)return <LoadingSpinner/>;if(!sale||!receipt)return <Alert message={error||'Sale not found.'}/>;const width=Number(settings?.receipt_paper_width_mm??80);return <div className="space-y-6"><PageHeader title={sale.invoice_number||`Sale ${sale.id.slice(0,8)}`} description={`Invoice details and ${width}mm thermal receipt`} action={<div className="flex gap-2"><Link to="/sales"><Button variant="secondary"><ArrowLeft size={16}/>Back</Button></Link><Link to={`/returns/new?invoice=${encodeURIComponent(sale.invoice_number||'')}`}><Button variant="secondary"><RotateCcw size={16}/>Return / Exchange</Button></Link><Button onClick={handlePrint}><Printer size={16}/>Print Receipt</Button></div>}/>{error&&<Alert message={error}/>}<section className="glass-card mx-auto max-w-3xl p-5"><div className="relative z-10 grid gap-3 text-sm sm:grid-cols-2"><p>Date: {formatDateTime(sale.created_at)}</p><p>Customer: {sale.customer?.name||'Walk-in Customer'}</p><p>Payment: {sale.payment_method.replaceAll('_',' ')}</p><p>Total: {formatCurrency(Number(sale.total_amount))}</p></div></section>{import.meta.env.DEV&&<section className="glass-card mx-auto max-w-3xl p-4"><div className="relative z-10 flex flex-wrap items-center gap-2"><span className="text-sm text-dashboard-text-sub">Test Thermal Receipt:</span><Button size="sm" variant="secondary" onClick={()=>setTestCount(null)}>Actual</Button>{testCounts.map(count=><Button key={count} size="sm" variant="secondary" onClick={()=>setTestCount(count)}>{count} items</Button>)}</div></section>}<div className="screen-receipt-preview">{receipt}</div></div>}
