import { useCallback,useEffect,useState } from 'react'; import { Download,FileDown,FileSpreadsheet } from 'lucide-react';
import { Alert,Button,LoadingSpinner,PageHeader } from '../components/ui'; import { useAuth } from '../context/AuthContext';
import type { ReportInvoice,ReportPreset,ReportTab,SalesReportData,SalesReportFilters as Filters,SummaryRow } from '../types/salesReport';
import { getSalesReport,downloadBlob,exportWorkbook,toCsv } from '../services/salesReportService'; import { getErrorMessage } from '../utils/errors';
import { downloadSalesReportPdf } from '../services/salesReportPdf';
import { SalesReportFilters,presetDates } from '../components/reports/SalesReportFilters'; import { SalesSummaryCards } from '../components/reports/SalesSummaryCards'; import { DetailedInvoiceTable } from '../components/reports/DetailedInvoiceTable'; import { ReportSummaryTable } from '../components/reports/ReportSummaryTable'; import { SalesPaymentSummary } from '../components/reports/SalesPaymentSummary'; import { SalesReportCharts } from '../components/reports/SalesReportCharts'; import { SaleDetailsModal } from '../components/reports/SaleDetailsModal'; import { SalesReportPrintView } from '../components/reports/SalesReportPrintView';

function aggregate(invoices:ReportInvoice[],kind:'product'|'customer'|'cashier'|'category'|'brand'):SummaryRow[]{const map=new Map<string,SummaryRow&{ids:Set<string>;missing:boolean}>();for(const x of invoices){if(x.status==='cancelled')continue;const list=kind==='customer'||kind==='cashier'?[{key:kind==='customer'?x.customer_name:x.cashier_name,label:kind==='customer'?x.customer_name:x.cashier_name,sold:x.total_quantity,returned:0,netQty:x.total_quantity,gross:x.gross_amount,disc:x.item_discount+x.invoice_discount,returns:x.returned_amount,net:x.net_amount,cost:x.cost_of_goods,profit:x.gross_profit}]:x.items.map(i=>{const label=kind==='product'?`${i.product_name}${i.size?' · '+i.size:''}${i.colour?' · '+i.colour:''}`:kind==='category'?(i.category||'Uncategorized'):(i.brand||'Unbranded');return{key:kind==='product'?`${i.product_name}|${i.barcode}|${i.size}|${i.colour}`:label,label,sold:i.quantity_sold,returned:i.quantity_returned,netQty:i.net_quantity,gross:i.original_value,disc:i.discount,returns:i.returned_value,net:i.net_revenue,cost:i.cost_total,profit:i.profit}});for(const e of list){let r=map.get(e.key);if(!r){r={key:e.key,label:e.label,invoices:0,quantity_sold:0,quantity_returned:0,net_quantity:0,gross_sales:0,discounts:0,returns:0,net_sales:0,amount_paid:0,outstanding:0,cost_of_goods:0,gross_profit:0,profit_margin:null,ids:new Set(),missing:false};map.set(e.key,r)}r.ids.add(x.id);r.quantity_sold+=e.sold;r.quantity_returned+=e.returned;r.net_quantity+=e.netQty;r.gross_sales+=e.gross;r.discounts+=e.disc;r.returns+=e.returns;r.net_sales+=e.net;if(e.cost==null)r.missing=true;else r.cost_of_goods=(r.cost_of_goods??0)+e.cost;if(e.profit!=null)r.gross_profit=(r.gross_profit??0)+e.profit;if(kind==='customer'||kind==='cashier'){r.amount_paid+=x.amount_paid;r.outstanding+=x.outstanding}}}return [...map.values()].map(({ids,missing,...r})=>({...r,invoices:ids.size,cost_of_goods:missing?null:r.cost_of_goods,gross_profit:missing?null:r.gross_profit,profit_margin:missing||!r.net_sales?null:(r.gross_profit??0)/r.net_sales*100})).sort((a,b)=>b.net_sales-a.net_sales)}

export function SalesReportPage(){const {profile}=useAuth();const [preset,setPreset]=useState<ReportPreset>('this_month');const [filters,setFilters]=useState<Filters>(presetDates('this_month'));const [data,setData]=useState<SalesReportData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string>();const [tab,setTab]=useState<ReportTab>('invoices');const [selected,setSelected]=useState<ReportInvoice|null>(null);const showProfit=profile?.role==='admin';
 const load=useCallback(async()=>{setLoading(true);setError(undefined);try{const d=await getSalesReport(filters);d.invoices=d.invoices.map(x=>({...x,payments:d.payments.filter(p=>p.sale_id===x.id),returns:d.returns.filter(r=>r.sale_id===x.id)}));d.products=aggregate(d.invoices,'product');d.customers=aggregate(d.invoices,'customer');d.cashiers=aggregate(d.invoices,'cashier');d.categories=aggregate(d.invoices,'category');d.brands=aggregate(d.invoices,'brand');setData(d)}catch(e){setError(getErrorMessage(e))}finally{setLoading(false)}},[filters]);useEffect(()=>{void load()},[]);
 const changePreset=(p:ReportPreset)=>{setPreset(p);if(p!=='custom')setFilters(f=>({...f,...presetDates(p)}))};const reset=()=>{setPreset('this_month');setFilters(presetDates('this_month'))};
 const csv=()=>{if(!data)return;const rows=tab==='payments'?data.payments.map(x=>[x.invoice_number,x.payment_method,x.amount,x.reference_number,x.payment_date]):data.invoices.map(x=>[x.invoice_number,x.created_at,x.customer_name,x.cashier_name,x.gross_amount,x.net_amount,x.cost_of_goods,x.gross_profit,x.amount_paid,x.outstanding,x.status]);downloadBlob(`sales-${tab}.csv`,toCsv(tab==='payments'?['Invoice','Method','Amount','Reference','Date']:['Invoice','Date','Customer','Cashier','Gross','Net','Cost','Profit','Paid','Outstanding','Status'],rows),'text/csv;charset=utf-8')};
 const tabs:Array<[ReportTab,string]>=[['invoices','Invoices'],['products','Product Sales'],['customers','Customer Summary'],['cashiers','Cashier Summary'],['categories','Category Summary'],['brands','Brand Summary'],['payments','Payments']];
 const downloadPdf=()=>data&&downloadSalesReportPdf(data,filters,profile?.full_name||profile?.email||'User');
 return <div className="sales-report-page space-y-6"><div className="print-hidden"><PageHeader title="Detailed Sales Report" description="Historical cost, returns, payments, receivables and profitability from Supabase." action={<div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!data} onClick={csv}><Download size={16}/>CSV</Button>{showProfit&&<Button variant="secondary" disabled={!data} onClick={()=>data&&exportWorkbook(data)}><FileSpreadsheet size={16}/>Excel</Button>}<Button variant="secondary" disabled={!data} onClick={()=>void downloadPdf()}><FileDown size={16}/>Download PDF</Button></div>}/></div><SalesReportFilters value={filters} preset={preset} onPreset={changePreset} onChange={f=>{setFilters(f);setPreset('custom')}} onApply={()=>void load()} onReset={reset}/>{error&&<Alert message={error}/>} {loading?<LoadingSpinner/>:data&&<><div className="print-hidden space-y-6"><SalesSummaryCards s={data.summary} showProfit={showProfit}/><SalesReportCharts invoices={data.invoices}/><div className="flex gap-2 overflow-x-auto border-b border-white/10">{tabs.map(([k,l])=><button key={k} className={`whitespace-nowrap px-4 py-3 text-sm ${tab===k?'border-b-2 border-sky-400 text-white':'text-dashboard-text-sub'}`} onClick={()=>setTab(k)}>{l}</button>)}</div>{tab==='invoices'&&<DetailedInvoiceTable rows={data.invoices} onView={setSelected} showProfit={showProfit}/>} {tab==='products'&&<ReportSummaryTable title="Product Sales Details" rows={data.products} showProfit={showProfit}/>} {tab==='customers'&&<ReportSummaryTable title="Customer Summary" rows={data.customers} showProfit={showProfit}/>} {tab==='cashiers'&&<ReportSummaryTable title="Cashier Summary" rows={data.cashiers} showProfit={showProfit}/>} {tab==='categories'&&<ReportSummaryTable title="Category Summary" rows={data.categories} showProfit={showProfit}/>} {tab==='brands'&&<ReportSummaryTable title="Brand Summary" rows={data.brands} showProfit={showProfit}/>} {tab==='payments'&&<SalesPaymentSummary data={data}/>}</div><SalesReportPrintView data={data} filters={filters} generatedBy={profile?.full_name||profile?.email||'User'}/><SaleDetailsModal sale={selected} onClose={()=>setSelected(null)} showProfit={showProfit}/></>}</div>}
