import type { ReactNode } from 'react';
import type { SaleWithRelations } from '../../services/salesService';
import type { StoreSettings } from '../../types';
import type { SalesReturnRecord } from '../../types/salesReturn';
import type { CashRegisterSummary } from '../../types/cashRegister';
import { formatCurrency } from '../../utils/format';
const money=(v:number)=>formatCurrency(Number(v)); const title=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export function ThermalReceiptHeader({title:heading,settings,subtitle}:{title?:string;settings?:StoreSettings|null;subtitle?:string}){return <header className="thermal-header">{settings?.receipt_show_logo&&settings.logo_url&&<img className="thermal-header-logo" src={settings.logo_url} alt=""/>}<h1>{heading||settings?.store_name||'Shoe Shop'}</h1>{subtitle&&<h2>{subtitle}</h2>}{settings?.address&&<p>{settings.address}</p>}{settings?.phone&&<p>Tel: {settings.phone}</p>}</header>}
export function ThermalRow({name,value,strong=false}:{name:string;value:ReactNode;strong?:boolean}){return <div className={`thermal-row${strong?' thermal-row--strong':''}`}><span>{name}</span><span>{value}</span></div>}
export function ThermalReceiptItem({name,itemNumber,size,colour,quantity,unitPrice,discount,total}:{name:string;itemNumber?:string|null;size?:string|null;colour?:string|null;quantity:number;unitPrice:number;discount?:number;total:number}){return <article className="thermal-item"><div className="thermal-item-name">{name}</div>{itemNumber&&<div className="thermal-muted">Item: {itemNumber}</div>}<div className="thermal-muted">{size||'—'} / {colour||'—'}</div><ThermalRow name={`${quantity} x ${money(unitPrice)}`} value={money(total)}/>{Number(discount)>0&&<ThermalRow name="Item discount" value={`-${money(Number(discount))}`}/>}</article>}
export function ThermalReceiptTotals({children}:{children:ReactNode}){return <section className="thermal-totals thermal-rule">{children}</section>}
export function ThermalReceiptFooter({message}:{message?:string|null}){return <footer className="thermal-footer thermal-rule"><strong>THANK YOU</strong>{message&&<p>{message}</p>}</footer>}
export function ThermalReceipt({sale,settings}:{sale:SaleWithRelations;settings?:StoreSettings|null}){const date=new Date(sale.created_at),paid=Number(sale.amount_tendered??sale.paid_amount??0),change=Number(sale.change_due??Math.max(paid-Number(sale.total_amount),0)),due=Number(sale.balance_due??Math.max(Number(sale.total_amount)-Number(sale.paid_amount),0));return <div className="thermal-receipt" role="document"><ThermalReceiptHeader settings={settings}/><section className="thermal-meta thermal-rule"><ThermalRow name="Invoice" value={sale.invoice_number||sale.id.slice(0,8)}/><ThermalRow name="Date" value={date.toLocaleDateString()}/><ThermalRow name="Time" value={date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}/><ThermalRow name="Cashier" value={sale.cashier?.full_name||sale.cashier?.email||'Cashier'}/>{sale.customer&&<ThermalRow name="Customer" value={sale.customer.name}/>}</section><section className="thermal-items thermal-rule">{sale.sale_items.map(i=><ThermalReceiptItem key={i.id} name={i.product_name_snapshot||i.variant?.product?.name||'Unknown item'} itemNumber={(i.variant as unknown as {item_number?:string})?.item_number} size={i.size_snapshot||i.variant?.size} colour={i.color_snapshot||i.variant?.color} quantity={i.quantity} unitPrice={Number(i.selling_price)} discount={Number(i.discount_amount)} total={Number(i.line_total)}/>)}</section><ThermalReceiptTotals><ThermalRow name="Subtotal" value={money(Number(sale.subtotal))}/>{Number(sale.discount_amount)>0&&<ThermalRow name="Discount" value={`-${money(Number(sale.discount_amount))}`}/>} {Number(sale.tax_amount)!==0&&<ThermalRow name={sale.payment_method==='card'?'Card fee':'Tax'} value={money(Number(sale.tax_amount))}/>}<div className="thermal-total"><ThermalRow name="TOTAL" value={money(Number(sale.total_amount))} strong/></div><ThermalRow name="Payment" value={title(sale.payment_method)}/><ThermalRow name="Paid" value={money(paid)}/>{change>0&&<ThermalRow name="Change" value={money(change)}/>} {due>0&&<ThermalRow name="Outstanding" value={money(due)} strong/>}</ThermalReceiptTotals><ThermalReceiptFooter message={settings?.receipt_footer}/></div>}
export function ThermalReturnReceipt({record,settings}:{record:SalesReturnRecord;settings?:StoreSettings|null}){const d=new Date(record.return_date),total=record.sales_return_items.reduce((s,i)=>s+Number(i.return_total),0);return <div className="thermal-receipt" role="document"><ThermalReceiptHeader settings={settings} subtitle="RETURN RECEIPT"/><section className="thermal-meta thermal-rule"><ThermalRow name="Return" value={record.return_number}/><ThermalRow name="Original invoice" value={record.sale?.invoice_number||'—'}/><ThermalRow name="Date" value={d.toLocaleDateString()}/><ThermalRow name="Time" value={d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}/><ThermalRow name="Processed by" value={record.processor?.full_name||record.processor?.email||'Staff'}/>{record.customer&&<ThermalRow name="Customer" value={record.customer.name}/>}</section><section className="thermal-items thermal-rule">{record.sales_return_items.map(i=><ThermalReceiptItem key={i.id} name={i.product_name} size={i.size} colour={i.colour} quantity={i.quantity_returned} unitPrice={Number(i.return_unit_value)} total={Number(i.return_total)}/>)}</section><ThermalReceiptTotals><ThermalRow name="Return value" value={money(total)} strong/><ThermalRow name="Refund method" value={title(record.refund_method||'No refund')}/><ThermalRow name="Refund amount" value={money(Number(record.refund_amount))}/>{Number(record.store_credit_amount)>0&&<ThermalRow name="Store credit" value={money(Number(record.store_credit_amount))}/>}</ThermalReceiptTotals><ThermalReceiptFooter message="Please keep this receipt for your records."/></div>}
export function ThermalCashUpReceipt({summary,settings}:{summary:CashRegisterSummary;settings?:StoreSettings|null}){const expected=Number(summary.expected_cash??summary.expected_cash_live);return <div className="thermal-receipt" role="document"><ThermalReceiptHeader title="CASH UP REPORT" settings={settings}/><section className="thermal-meta thermal-rule"><ThermalRow name="Cashier" value={summary.cashier_name}/><ThermalRow name="Opened" value={new Date(summary.opening_time).toLocaleString()}/><ThermalRow name="Closed" value={summary.closing_time?new Date(summary.closing_time).toLocaleString():'Open'}/></section><ThermalReceiptTotals><ThermalRow name="Opening cash" value={money(Number(summary.opening_balance))}/><ThermalRow name="Cash sales" value={money(Number(summary.cash_sales))}/><ThermalRow name="Cash refunds" value={`-${money(Number(summary.cash_refunds))}`}/><ThermalRow name="Cash expenses" value={`-${money(Number(summary.cash_expenses))}`}/><div className="thermal-total"><ThermalRow name="Expected cash" value={money(expected)} strong/></div><ThermalRow name="Actual cash" value={summary.actual_cash==null?'—':money(Number(summary.actual_cash))}/>{summary.difference!=null&&<ThermalRow name="Difference" value={money(Number(summary.difference))} strong/>}</ThermalReceiptTotals><ThermalReceiptFooter message="End of cash up report"/></div>}
