-- Returns Report: one row per sales_returns.id with independently aggregated children.
CREATE OR REPLACE FUNCTION public.get_returns_report(p_start_date date DEFAULT NULL,p_end_date date DEFAULT NULL,p_search text DEFAULT NULL,p_return_type text DEFAULT NULL,p_status text DEFAULT NULL,p_customer_id uuid DEFAULT NULL,p_processor_id uuid DEFAULT NULL,p_restock_status text DEFAULT NULL,p_page integer DEFAULT 1,p_page_size integer DEFAULT 25,p_sort text DEFAULT 'newest') RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
WITH item_summary AS (
 SELECT i.return_id,count(i.id)::int item_lines,coalesce(sum(i.quantity_returned),0)::int returned_quantity,coalesce(sum(i.return_total),0) return_value,
 coalesce(sum(i.quantity_returned) FILTER(WHERE i.restock_item),0)::int restocked_quantity,coalesce(sum(i.quantity_returned) FILTER(WHERE NOT i.restock_item),0)::int non_restocked_quantity
 FROM public.sales_return_items i GROUP BY i.return_id
), refund_summary AS (
 SELECT f.return_id,coalesce(sum(f.amount),0) refunded_amount,string_agg(DISTINCT f.refund_method,', ') refund_method,string_agg(DISTINCT f.reference_number,', ') FILTER(WHERE f.reference_number IS NOT NULL) refund_reference
 FROM public.sale_refunds f GROUP BY f.return_id
), base AS (
 SELECT r.id return_id,r.return_number,r.return_date,r.sale_id,s.invoice_number original_invoice,s.created_at invoice_date,r.customer_id,coalesce(c.name,'Walk-in Customer') customer_name,c.phone customer_phone,
 r.return_type,coalesce(i.item_lines,0) item_lines,coalesce(i.returned_quantity,0) returned_quantity,coalesce(i.return_value,0) return_value,
 coalesce(f.refunded_amount,r.refund_amount,0) refunded_amount,CASE WHEN r.return_type IN('size_exchange','colour_exchange','product_exchange') THEN coalesce(i.return_value,0) ELSE 0 END exchange_value,
 coalesce(i.restocked_quantity,0) restocked_quantity,coalesce(i.non_restocked_quantity,0) non_restocked_quantity,r.created_by processed_by_id,coalesce(pr.full_name,pr.email,'Unknown') processed_by,
 r.status,r.reason,r.created_at,coalesce(s.total_amount,0) original_total,coalesce(s.payment_method,'') payment_method,coalesce(f.refund_method,r.refund_method) refund_method,coalesce(f.refund_reference,r.refund_reference) refund_reference,
 r.replacement_sale_id,rs.invoice_number replacement_invoice,coalesce(r.additional_payment,0) additional_payment,coalesce(r.store_credit_amount,0) store_credit_amount
 FROM public.sales_returns r LEFT JOIN item_summary i ON i.return_id=r.id LEFT JOIN refund_summary f ON f.return_id=r.id LEFT JOIN public.sales s ON s.id=r.sale_id LEFT JOIN public.sales rs ON rs.id=r.replacement_sale_id LEFT JOIN public.customers c ON c.id=r.customer_id LEFT JOIN public.profiles pr ON pr.id=r.created_by
 WHERE (p_start_date IS NULL OR r.return_date::date>=p_start_date) AND (p_end_date IS NULL OR r.return_date::date<=p_end_date) AND (p_return_type IS NULL OR r.return_type=p_return_type) AND (p_status IS NULL OR r.status=p_status) AND (p_customer_id IS NULL OR r.customer_id=p_customer_id) AND (p_processor_id IS NULL OR r.created_by=p_processor_id)
 AND (nullif(btrim(p_search),'') IS NULL OR r.return_number ILIKE '%'||btrim(p_search)||'%' OR coalesce(s.invoice_number,'') ILIKE '%'||btrim(p_search)||'%' OR coalesce(c.name,'') ILIKE '%'||btrim(p_search)||'%' OR coalesce(c.phone,'') ILIKE '%'||btrim(p_search)||'%' OR EXISTS(SELECT 1 FROM public.sales_return_items si LEFT JOIN public.product_variants pv ON pv.id=si.original_variant_id LEFT JOIN public.products p ON p.id=pv.product_id WHERE si.return_id=r.id AND (si.product_name ILIKE '%'||btrim(p_search)||'%' OR coalesce(si.barcode_number,'') ILIKE '%'||btrim(p_search)||'%' OR coalesce(p.item_article,'') ILIKE '%'||btrim(p_search)||'%')))
), filtered AS (SELECT * FROM base WHERE p_restock_status IS NULL OR (p_restock_status='restocked' AND restocked_quantity>0) OR (p_restock_status='not_restocked' AND non_restocked_quantity>0)),
totals AS (SELECT count(*)::int total_returns,count(*) FILTER(WHERE status='completed')::int return_transactions,coalesce(sum(returned_quantity) FILTER(WHERE status='completed'),0)::int quantity_returned,coalesce(sum(return_value) FILTER(WHERE status='completed'),0) return_value,coalesce(sum(refunded_amount) FILTER(WHERE status='completed'),0) refunded_amount,coalesce(sum(exchange_value) FILTER(WHERE status='completed'),0) exchange_value,coalesce(sum(restocked_quantity) FILTER(WHERE status='completed'),0)::int restocked_quantity,coalesce(sum(non_restocked_quantity) FILTER(WHERE status='completed'),0)::int non_restocked_quantity FROM filtered),
product_summary AS (SELECT si.product_name,MAX(p.item_article) article,sum(si.quantity_returned)::int returned_quantity,sum(si.return_total) return_value FROM public.sales_return_items si JOIN filtered f ON f.return_id=si.return_id LEFT JOIN public.product_variants pv ON pv.id=si.original_variant_id LEFT JOIN public.products p ON p.id=pv.product_id WHERE f.status='completed' GROUP BY si.product_name ORDER BY returned_quantity DESC,si.product_name LIMIT 8),
reason_summary AS (SELECT reason,count(*)::int transactions FROM filtered WHERE status='completed' AND nullif(btrim(reason),'') IS NOT NULL GROUP BY reason ORDER BY transactions DESC,reason),
paged AS (SELECT * FROM filtered ORDER BY CASE WHEN p_sort='oldest' THEN return_date END ASC,CASE WHEN p_sort='number_asc' THEN return_number END ASC,CASE WHEN p_sort='number_desc' THEN return_number END DESC,CASE WHEN p_sort='invoice_asc' THEN original_invoice END ASC,CASE WHEN p_sort='value_desc' THEN return_value END DESC,CASE WHEN p_sort='value_asc' THEN return_value END ASC,CASE WHEN p_sort='customer_asc' THEN customer_name END ASC,CASE WHEN p_sort='status_asc' THEN status END ASC,CASE WHEN p_sort='newest' OR p_sort IS NULL THEN return_date END DESC,created_at DESC,return_id LIMIT least(greatest(p_page_size,1),100) OFFSET(greatest(p_page,1)-1)*least(greatest(p_page_size,1),100))
SELECT jsonb_build_object('rows',coalesce((SELECT jsonb_agg(to_jsonb(paged)) FROM paged),'[]'::jsonb),'total',(SELECT count(*) FROM filtered),'summary',to_jsonb(totals),'products',coalesce((SELECT jsonb_agg(to_jsonb(product_summary)) FROM product_summary),'[]'::jsonb),'reasons',coalesce((SELECT jsonb_agg(to_jsonb(reason_summary)) FROM reason_summary),'[]'::jsonb)) FROM totals;
$$;
REVOKE ALL ON FUNCTION public.get_returns_report(date,date,text,text,text,uuid,uuid,text,integer,integer,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_returns_report(date,date,text,text,text,uuid,uuid,text,integer,integer,text) TO authenticated;
