-- Read-only Cashup Report using the existing register-session ownership and time boundaries.
CREATE OR REPLACE FUNCTION public.get_cashup_report(p_start_date date DEFAULT NULL,p_end_date date DEFAULT NULL,p_search text DEFAULT NULL,p_cashier_id uuid DEFAULT NULL,p_status text DEFAULT NULL,p_page integer DEFAULT 1,p_page_size integer DEFAULT 25,p_sort text DEFAULT 'newest')RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
WITH sessions AS(SELECT s.*,coalesce(pr.full_name,pr.email,'Cashier')cashier_name,'CS-'||upper(substr(replace(s.id::text,'-',''),1,8))cashup_number,coalesce(s.closing_time,now()+interval'1 second')session_end FROM public.cash_register_sessions s LEFT JOIN public.profiles pr ON pr.id=s.user_id WHERE(p_start_date IS NULL OR s.opening_time::date>=p_start_date)AND(p_end_date IS NULL OR s.opening_time::date<=p_end_date)AND(p_cashier_id IS NULL OR s.user_id=p_cashier_id)),
sale_items AS(SELECT si.sale_id,count(si.id)::int items,sum(si.quantity)::int quantity,sum(coalesce(si.line_subtotal,si.selling_price*si.quantity))gross,sum(coalesce(si.discount_amount,0))item_discount FROM public.sale_items si GROUP BY si.sale_id),
session_sales AS(SELECT ss.id session_id,count(sa.id)::int total_invoices,coalesce(sum(si.quantity),0)::int items_sold,coalesce(sum(si.quantity),0)::int quantity_sold,coalesce(sum(si.gross),0)gross_sales,coalesce(sum(coalesce(sa.discount_amount,0)),0)discounts,coalesce(sum(sa.total_amount),0)total_sales FROM sessions ss LEFT JOIN public.sales sa ON sa.user_id=ss.user_id AND sa.created_at>=ss.opening_time AND sa.created_at<ss.session_end AND sa.status IN('completed','partially_returned','fully_returned')LEFT JOIN sale_items si ON si.sale_id=sa.id GROUP BY ss.id),
payments AS(SELECT ss.id session_id,coalesce(sum(p.amount)FILTER(WHERE p.payment_method='cash'),0)cash_sales,coalesce(sum(p.amount)FILTER(WHERE p.payment_method='card'),0)card_sales,coalesce(sum(p.amount)FILTER(WHERE p.payment_method='bank_transfer'),0)bank_sales,coalesce(sum(p.amount)FILTER(WHERE p.payment_method NOT IN('cash','card','bank_transfer','credit')),0)other_sales FROM sessions ss LEFT JOIN public.sale_payments p ON p.received_by=ss.user_id AND p.payment_date>=ss.opening_time AND p.payment_date<ss.session_end GROUP BY ss.id),
sale_paid AS(SELECT ss.id session_id,sa.id sale_id,sa.total_amount,coalesce(sum(p.amount),0)paid FROM sessions ss JOIN public.sales sa ON sa.user_id=ss.user_id AND sa.created_at>=ss.opening_time AND sa.created_at<ss.session_end AND sa.status IN('completed','partially_returned','fully_returned')LEFT JOIN public.sale_payments p ON p.sale_id=sa.id GROUP BY ss.id,sa.id,sa.total_amount),credits AS(SELECT session_id,coalesce(sum(greatest(total_amount-paid,0)),0)credit_sales FROM sale_paid GROUP BY session_id),
refunds AS(SELECT ss.id session_id,coalesce(sum(r.amount)FILTER(WHERE r.refund_method='cash'),0)cash_refunds FROM sessions ss LEFT JOIN public.sale_refunds r ON r.refunded_by=ss.user_id AND r.refund_date>=ss.opening_time AND r.refund_date<ss.session_end GROUP BY ss.id),expenses AS(SELECT ss.id session_id,coalesce(sum(e.amount),0)cash_expenses FROM sessions ss LEFT JOIN public.cash_register_expenses e ON e.session_id=ss.id GROUP BY ss.id),
rows0 AS(SELECT s.id session_id,s.cashup_number,s.user_id,s.cashier_name,s.opening_time,s.closing_time,s.opening_balance opening_cash,coalesce(v.total_invoices,0)total_invoices,coalesce(v.items_sold,0)items_sold,coalesce(v.gross_sales,0)gross_sales,coalesce(v.discounts,0)discounts,coalesce(v.total_sales,0)total_sales,p.cash_sales,p.card_sales,p.bank_sales,coalesce(c.credit_sales,0)credit_sales,p.other_sales,r.cash_refunds,e.cash_expenses,s.opening_balance+p.cash_sales-r.cash_refunds-e.cash_expenses expected_cash,s.actual_cash counted_cash,CASE WHEN s.actual_cash IS NULL THEN NULL ELSE s.actual_cash-(s.opening_balance+p.cash_sales-r.cash_refunds-e.cash_expenses)END difference,s.status,CASE WHEN s.status='open'THEN'open'WHEN abs(s.actual_cash-(s.opening_balance+p.cash_sales-r.cash_refunds-e.cash_expenses))<=.01 THEN'balanced'WHEN s.actual_cash-(s.opening_balance+p.cash_sales-r.cash_refunds-e.cash_expenses)<0 THEN'short'ELSE'over'END difference_status,s.notes FROM sessions s JOIN session_sales v ON v.session_id=s.id JOIN payments p ON p.session_id=s.id LEFT JOIN credits c ON c.session_id=s.id JOIN refunds r ON r.session_id=s.id JOIN expenses e ON e.session_id=s.id),
filtered AS(SELECT * FROM rows0 r WHERE(p_status IS NULL OR r.status=p_status OR r.difference_status=p_status)AND(nullif(btrim(p_search),'')IS NULL OR r.cashup_number ILIKE'%'||btrim(p_search)||'%'OR r.cashier_name ILIKE'%'||btrim(p_search)||'%'OR EXISTS(SELECT 1 FROM public.sales sa WHERE sa.user_id=r.user_id AND sa.created_at>=r.opening_time AND sa.created_at<coalesce(r.closing_time,now()+interval'1 second')AND sa.invoice_number ILIKE'%'||btrim(p_search)||'%'))),
summary AS(SELECT count(*)::int sessions,coalesce(sum(total_sales),0)total_sales,coalesce(sum(cash_sales),0)cash_sales,coalesce(sum(card_sales),0)card_sales,coalesce(sum(bank_sales),0)bank_sales,coalesce(sum(credit_sales),0)credit_sales,coalesce(sum(expected_cash),0)expected_cash,coalesce(sum(difference)FILTER(WHERE status='closed'),0)cash_difference FROM filtered),daily AS(SELECT opening_time::date date,count(*)::int sessions,sum(total_sales)sales,sum(cash_sales)cash,sum(card_sales)card,sum(bank_sales)transfer,sum(credit_sales)credit,sum(expected_cash)expected_cash,coalesce(sum(counted_cash),0)counted_cash,coalesce(sum(difference),0)difference FROM filtered GROUP BY opening_time::date),cashiers AS(SELECT user_id::text key,cashier_name name,count(*)::int sessions,sum(total_invoices)::int invoices,sum(total_sales)sales,sum(cash_sales)cash_collected,coalesce(sum(difference),0)difference FROM filtered GROUP BY user_id,cashier_name),paged AS(SELECT * FROM filtered ORDER BY CASE WHEN p_sort='oldest'THEN opening_time END ASC,CASE WHEN p_sort='sales_desc'THEN total_sales END DESC,CASE WHEN p_sort='difference_asc'THEN difference END ASC,CASE WHEN p_sort='cashier_asc'THEN cashier_name END ASC,CASE WHEN p_sort='newest'OR p_sort IS NULL THEN opening_time END DESC,session_id LIMIT least(greatest(p_page_size,1),100)OFFSET(greatest(p_page,1)-1)*least(greatest(p_page_size,1),100))
SELECT jsonb_build_object('rows',coalesce((SELECT jsonb_agg(to_jsonb(paged))FROM paged),'[]'::jsonb),'total',(SELECT count(*)FROM filtered),'summary',to_jsonb(summary),'daily',coalesce((SELECT jsonb_agg(to_jsonb(daily)ORDER BY date)FROM daily),'[]'::jsonb),'cashiers',coalesce((SELECT jsonb_agg(to_jsonb(cashiers)ORDER BY sales DESC)FROM cashiers),'[]'::jsonb))FROM summary;
$$;
REVOKE ALL ON FUNCTION public.get_cashup_report(date,date,text,uuid,text,integer,integer,text)FROM PUBLIC;GRANT EXECUTE ON FUNCTION public.get_cashup_report(date,date,text,uuid,text,integer,integer,text)TO authenticated;
