-- Replacement merchandise is revenue and COGS; the original item remains a return reversal.
ALTER FUNCTION public.profit_report_item_rows(jsonb) RENAME TO profit_report_original_item_rows;
CREATE FUNCTION public.profit_report_item_rows(p_filters jsonb DEFAULT '{}'::jsonb)
RETURNS TABLE(sale_item_id uuid,sale_id uuid,invoice_number text,sale_date timestamptz,customer_name text,cashier_id uuid,cashier_name text,payment_method text,status text,product_id uuid,product_name text,article text,category_id uuid,category_name text,brand_id uuid,brand_name text,variant_id uuid,size text,colour text,barcode text,quantity integer,returned_quantity integer,net_quantity integer,selling_price numeric,gross_sales numeric,item_discount numeric,invoice_discount numeric,discount numeric,returned_value numeric,net_revenue numeric,unit_cost numeric,sold_cogs numeric,reversed_cogs numeric,cogs numeric,profit numeric,margin numeric)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
 SELECT * FROM public.profit_report_original_item_rows(p_filters)
 UNION ALL
 SELECT sri.id,sr.id,sr.return_number,sr.return_date,coalesce(c.name,'Walk-in Customer'),sr.created_by,coalesce(pr.full_name,pr.email,'Unknown'),coalesce(sr.exchange_payment_method,'even'),'exchange',p.id,coalesce(sri.replacement_product_name,p.name,'Unknown Product'),p.item_article,p.category_id,coalesce(ca.name,'Uncategorized'),p.brand_id,coalesce(b.name,'Unbranded'),sri.replacement_variant_id,sri.replacement_size,sri.replacement_colour,sri.replacement_barcode_number,coalesce(sri.replacement_quantity,0)::int,0,coalesce(sri.replacement_quantity,0)::int,coalesce(sri.replacement_selling_price,0),coalesce(sri.replacement_selling_price,0)*coalesce(sri.replacement_quantity,0),coalesce(sri.replacement_discount_amount,0),0,coalesce(sri.replacement_discount_amount,0),0,coalesce(sri.replacement_value,0),sri.replacement_cost_price,CASE WHEN sri.replacement_cost_price IS NULL THEN NULL ELSE sri.replacement_cost_price*coalesce(sri.replacement_quantity,0) END,0,CASE WHEN sri.replacement_cost_price IS NULL THEN NULL ELSE sri.replacement_cost_price*coalesce(sri.replacement_quantity,0) END,CASE WHEN sri.replacement_cost_price IS NULL THEN NULL ELSE coalesce(sri.replacement_value,0)-sri.replacement_cost_price*coalesce(sri.replacement_quantity,0) END,CASE WHEN coalesce(sri.replacement_value,0)=0 OR sri.replacement_cost_price IS NULL THEN 0 ELSE (coalesce(sri.replacement_value,0)-sri.replacement_cost_price*coalesce(sri.replacement_quantity,0))/sri.replacement_value*100 END
 FROM public.sales_return_items sri JOIN public.sales_returns sr ON sr.id=sri.return_id AND sr.status='completed' AND sr.return_type='product_exchange' JOIN public.sales s ON s.id=sr.sale_id LEFT JOIN public.customers c ON c.id=sr.customer_id LEFT JOIN public.profiles pr ON pr.id=sr.created_by LEFT JOIN public.product_variants pv ON pv.id=sri.replacement_variant_id LEFT JOIN public.products p ON p.id=pv.product_id LEFT JOIN public.categories ca ON ca.id=p.category_id LEFT JOIN public.brands b ON b.id=p.brand_id
 WHERE (coalesce(p_filters->>'startDate','')='' OR sr.return_date>=((p_filters->>'startDate')::date::timestamp AT TIME ZONE 'Asia/Colombo')) AND (coalesce(p_filters->>'endDate','')='' OR sr.return_date<(((p_filters->>'endDate')::date+1)::timestamp AT TIME ZONE 'Asia/Colombo')) AND (coalesce(p_filters->>'categoryId','')='' OR p.category_id=(p_filters->>'categoryId')::uuid) AND (coalesce(p_filters->>'brandId','')='' OR p.brand_id=(p_filters->>'brandId')::uuid) AND (coalesce(p_filters->>'productId','')='' OR p.id=(p_filters->>'productId')::uuid) AND (coalesce(p_filters->>'paymentMethod','')='' OR sr.exchange_payment_method=p_filters->>'paymentMethod') AND (coalesce(p_filters->>'cashierId','')='' OR sr.created_by=(p_filters->>'cashierId')::uuid) AND (coalesce(p_filters->>'search','')='' OR sr.return_number ILIKE '%'||(p_filters->>'search')||'%' OR s.invoice_number ILIKE '%'||(p_filters->>'search')||'%' OR coalesce(c.name,'') ILIKE '%'||(p_filters->>'search')||'%' OR coalesce(sri.replacement_product_name,'') ILIKE '%'||(p_filters->>'search')||'%' OR coalesce(sri.replacement_barcode_number,'') ILIKE '%'||(p_filters->>'search')||'%');
$$;
REVOKE ALL ON FUNCTION public.profit_report_item_rows(jsonb),public.profit_report_original_item_rows(jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.profit_report_item_rows(jsonb),public.profit_report_original_item_rows(jsonb) TO authenticated;
